ec: Add the analysis tool for firmware stack usage.
Add a static analysis tool for firmware stack usage.
Add an new Makefile rule to analyze the stack usages of firmwares.

Details about the tool can be found in extra/stack_analyzer/README.md.

BUG=chromium:648840
BRANCH=none
TEST=extra/stack_analyzer/stack_analyzer_unittest.py

Change-Id: Ifb1b5f5ad6be8f8b125b14d6ee03e25cb385895b
Signed-off-by: Che-yu Wu <cheyuw@google.com>

diff --git a/Makefile.rules b/Makefile.rules
--- a/Makefile.rules
+++ b/Makefile.rules
@@ -529,6 +529,25 @@ newsizes:
 			"$$((FILE_SIZE_CHANGE / FILES_CHANGED))"; \
 	fi
 
+.PHONY: analyzestack
+analyzestack:
+	@if [ "$(SECTION)" != "RO" ] && [ "$(SECTION)" != "RW" ]; then \
+		echo "Please specify SECTION=RO or RW"; \
+		exit 1; \
+	fi
+	@ELF=$(out)/$(SECTION)/ec.$(SECTION).elf; \
+	TASKLIST=$(out)/$(SECTION)/ec.$(SECTION).tasklist; \
+	if [ ! -f "$$ELF" ]; then \
+		echo "Some files are missing.  Are they built?"; \
+		exit 1; \
+	fi; \
+	$(CPP) -P -DSECTION_IS_$(SECTION) \
+		-I$(BDIR) -DBOARD_$(UC_BOARD) -D_MAKEFILE_DETAIL \
+		-imacros $(PROJECT).tasklist include/task_filter.h \
+		> "$$TASKLIST" && \
+	extra/stack_analyzer/stack_analyzer.py --objdump "$(OBJDUMP)" \
+	        --addr2line "$(ADDR2LINE)" "$$ELF" "$$TASKLIST"
+
 .SECONDARY:
 
 -include $(deps)
