flash_fp_mcu: Add unbind/bind dev functionality
These help with development and testing.
Doing these steps manually is very cumbersome, since there are
a few levels of indirection when resolving the device/driver name.
Then, you need to determine what the raw device interface might be.

Examples:

* Need to ask the kernel to try to rebind the cros-ec driver:
  flash_fp_mcu --unbind cros-ec --bind cros-ec
* Need to debug some gpio issue that is making the FPMCU unresponsive
  to the cros-ec driver:
  flash_fp_mcu --unbind cros-ec --bind raw
  # Manually twiddle gpios and keep running stm32mon to see if
  # bootloader is available.

BRANCH=none
BUG=none
TEST=# Dratini
     flash_fp_mcu --unbind cros-ec --bind raw
     ls -al /dev/spi*
     flash_fp_mcu --unbind raw  --bind cros-ec
     ls -al /dev/cros_fp
TEST=# Dratini
     flash_fp_mcu --unbind cros-ec --bind cros-ec
     ls -al /dev/cros_fp
TEST=flash_fp_mcu

Signed-off-by: Craig Hesling <hesling@chromium.org>
Change-Id: I8b49c7bcce079fe9293b83a39a580268692a1056

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -18,10 +18,13 @@ DEFINE_boolean 'remove_flash_write_protect' "${FLAGS_TRUE}" \
   'Remove flash write protection while performing command' 'u'
 DEFINE_integer 'retries' "${DEFAULT_RETRIES}" 'Specify number of retries' 'R'
 DEFINE_integer 'baudrate' "${STM32MON_SERIAL_BAUDRATE}" 'Specify UART baudrate' 'B'
+# Diagnostic commands
 DEFINE_boolean 'hello' "${FLAGS_FALSE}" 'Only ping the bootloader' 'H'
+DEFINE_string  'bind'   '' 'Force binding the "cros-ec" or "raw" interface.'
+DEFINE_string  'unbind' '' 'Force unbinding the "cros-ec" or "raw" interface.'
 FLAGS_HELP="Usage: ${0} [flags] [ec.bin]"
 
-#        EXIT_SUCCESS=0
+readonly EXIT_SUCCESS=0
 #        EXIT_FAILURE=1
 #        EXIT_BASHBUILTIN=2
 readonly EXIT_ARGUMENT=3
@@ -552,6 +555,24 @@ main() {
     if [[ "${FLAGS_read}" -eq "${FLAGS_TRUE}" ]]; then
       filename="/tmp/fpmcu-fw-$(date --iso-8601=seconds).bin"
     fi
+  fi
+
+  # Handle unbind/bind arguments that do not require invoking stm32mon.
+  if [[ -n "${FLAGS_unbind}" ]]; then
+    if ! driver "${TRANSPORT}" unbind "${FLAGS_unbind}"; then
+      echo "Failed to unbind driver '${FLAGS_unbind}'" >&2
+      exit "${EXIT_RUNTIME}"
+    fi
+  fi
+  if [[ -n "${FLAGS_bind}" ]]; then
+    if ! driver "${TRANSPORT}" bind "${FLAGS_bind}"; then
+      echo "Failed to bind driver '${FLAGS_bind}'" >&2
+      exit "${EXIT_RUNTIME}"
+    fi
+    echo "${DEVICE}"
+  fi
+  if [[ -n "${FLAGS_unbind}" ]] || [[ -n "${FLAGS_bind}" ]]; then
+    exit "${EXIT_SUCCESS}"
   fi
 
   # Check that the gpiochip exists
