flash_fp_mcu: add support for fatcat
**** WORK-IN-PROGRESS ****

BUG=None
TEST=None

Change-Id: I84ebb3a5c66c944df9ccb76499b7ea6e4e67ae7b

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -1146,6 +1146,43 @@ config_brox() {
   esac
 }
 
+config_fatcat() {
+  readonly TRANSPORT="SPI"
+  readonly DEVICE="/dev/spidev0.0"
+
+  # See kernel/v6.12/drivers/pinctrl/intel/pinctrl-meteorlake.c
+  # for pin name and pin number.
+  # Examine `cat /sys/kernel/debug/pinctrl/INTC1083:00/gpio-ranges` on a
+  # fatcat device to determine gpio number from pin number.
+  # For example: GPP_B11, the pin number is 215 from the pinctrl-meteorlake.c.
+  # From the gpio-ranges, the gpio value is 925 + (215-204) = 936
+
+  local gpiochip_dev_path="pci0000:00/INTC1083:00/gpio"
+  local gpiobase
+  if ! gpiobase=$(get_sysfs_gpiochip_base "${gpiochip_dev_path}"); then
+    echo "Unable to find gpio chip base"
+    return "${EXIT_PRECONDITION}"
+  fi
+
+  readonly GPIO_CHIP="gpiochip${gpiobase}"
+
+  local model
+  model=$(cros_config / name)
+  case "${model}" in
+    *)
+      # FPMCU RST_ODL is on GPP_C23 = 64 + (52 - 29) = 87
+      local gpionrst=87
+      readonly GPIO_NRST=$(( gpionrst + gpiobase ))
+      # FPMCU BOOT0 is on GPP_C22 = 64 + (51 - 29) = 86
+      local gpioboot=86
+      readonly GPIO_BOOT0=$(( gpioboot + gpiobase ))
+      # FP_PWR_EN is on GPP_B11 = 352 + (215-204) = 363
+      local gpiopwren=363
+      readonly GPIO_PWREN=$(( gpiopwren + gpiobase ))
+      ;;
+  esac
+}
+
 main() {
   local filename="$1"
   local chip_type
