flash_ec: add "--read" and "--verify" flags for stm32 chip.
"--read" takes a following string as a path to store the image file.
If it is specified, flash_ec reads only an EC firmware image and store
it to the given path.

"--verify" lets flash_ec read EC firmware image after flashing it, and
compare the read image to the source image to check if they match.

These two flags are supported for stm32 chip only for now.

BUG=b:112163028
BRANCH=none
TEST=manually ran flash_ec on scarlet.
util/flash_ec --board scarlet --image ${IMG_PATH} --verify
 --bitbang_rate 57600
util/flash_ec --board scarlet --read ${TEMP_IMG_PATH}
 --bitbang_rate 57600

Change-Id: I0913da7b8bf51313c7ff758a1ed3250a88c13b54
Signed-off-by: Namyoon Woo <namyoon@chromium.org>

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -11,6 +11,7 @@ EC_DIR="$(readlink -f "${SCRIPT_DIR}/..")"
 if [[ "$(basename "${EC_DIR}")" != "ec" ]]; then
 	EC_DIR=
 fi
+TEMP_DIR=""
 
 # Loads script libraries.
 . "/usr/share/misc/shflags" || exit 1
@@ -228,12 +229,17 @@ DEFINE_integer port "${DEFAULT_PORT}" \
 	"Port to communicate to servo on."
 DEFINE_boolean raiden "${FLAGS_FALSE}" \
 	"Use raiden_debug_spi programmer"
+DEFINE_string read "" "Full pathname to save the firmware image read from EC. "\
+"STM32 chip only is supported for now."
 DEFINE_boolean ro "${FLAGS_FALSE}" \
 	"Write only the read-only partition"
 DEFINE_integer timeout 600 \
 	"Timeout for flashing the EC, measured in seconds."
 DEFINE_boolean verbose "${FLAGS_FALSE}" \
 	"Verbose hw control logging"
+DEFINE_boolean verify "${FLAGS_FALSE}" \
+	"Read the image back from EC and compare to the source image. "\
+"STM32 chip only is supported for now."
 
 # Parse command line
 FLAGS_HELP="usage: $0 [flags]"
@@ -378,6 +384,12 @@ fi
 
 if [ "${CHIP}" = "stm32_dfu" -o "${CHIP}" = "it83xx" ]; then
 	NEED_SERVO="no"
+fi
+
+if [[ "${CHIP}" != "stm32" ]]; then
+	if [[ -n ${FLAGS_read} || ${FLAGS_verify} == ${FLAGS_TRUE} ]]; then
+		die "The flag is not yet supported on ${CHIP}."
+	fi
 fi
 
 servo_has_warm_reset() {
@@ -525,6 +537,11 @@ cleanup() {
 		kill -CONT ${pid}
 	done
 
+	# if temp dir exists, then delete
+	if [[ -n ${TEMP_DIR} ]]; then
+		rm -rf ${TEMP_DIR} 1>&2 2>/dev/null
+	fi
+
 	if [ "${CHIP}" == "it83xx" ] ; then
 		info "Reinitialize ftdi_i2c interface"
 		dut_control ftdii2c_cmd:init
@@ -543,7 +560,6 @@ cleanup() {
 			# Turn off servo i2c mux
 			dut_control i2c_mux_en:off
 		fi
-
 	fi
 	if [ "${CHIP}" == "stm32" -o "${CHIP}" == "npcx_uut" ] ; then
 		# Reconnect the EC-3PO interpreter to the UART.
@@ -980,13 +996,46 @@ function flash_stm32() {
 		info "Saving log in ${FLAGS_logfile}"
 	fi
 
-	# Unprotect flash, erase, and write
-	STM32MON_COMMAND="${STM32MON} -d ${EC_UART} ${log_option} -U -u -e -w"
-	if [ "${FLAGS_verbose}" = ${FLAGS_TRUE} ]; then
-		echo "${STM32MON_COMMAND}" "${IMG}"
+	local STM32MON_OPT="-d ${EC_UART} ${log_option}"
+	local IMG_READ=""
+	if [[ -z ${FLAGS_read} ]]; then
+		# Unprotect flash, erase, and write
+		local STM32MON_COMMAND="${STM32MON} ${STM32MON_OPT} -U -u -e -w"
+		if [[ "${FLAGS_verbose}" == ${FLAGS_TRUE} ]]; then
+			echo "${STM32MON_COMMAND}" "${IMG}"
+		fi
+		timeout -k 10 -s 9 "${FLAGS_timeout}" \
+			${STM32MON_COMMAND} "${IMG}"
+
+		if [[ ${FLAGS_verify} == ${FLAGS_TRUE} ]]; then
+			TEMP_DIR="$(mktemp -d --suffix=_${BOARD})"
+			IMG_READ="${TEMP_DIR}/ec.read.bin"
+		fi
+	else
+		IMG_READ="${FLAGS_read}"
 	fi
-	timeout -k 10 -s 9 "${FLAGS_timeout}" \
-		${STM32MON_COMMAND} "${IMG}"
+
+	# Read EC image.
+	if [[ -n ${IMG_READ} ]]; then
+		local STM32MON_READ_CMD="${STM32MON} ${STM32MON_OPT} -U -r"
+		if [[ "${FLAGS_verbose}" = ${FLAGS_TRUE} ]]; then
+			echo "${STM32MON_READ_CMD} ${IMG_READ}"
+		fi
+		timeout -k 10 -s 9 "${FLAGS_timeout}" \
+			${STM32MON_READ_CMD} ${IMG_READ}
+	fi
+
+	# Verify the flash by comparing the source image to the read image.
+	if [[ ${FLAGS_verify} == ${FLAGS_TRUE} ]]; then
+		if [[ "${FLAGS_verbose}" = ${FLAGS_TRUE} ]]; then
+			echo "diff ${IMG} ${IMG_READ}"
+		fi
+		diff ${IMG} ${IMG_READ} 1>&2 2>/dev/null
+		if [[ $? != 0 ]]; then
+			die "Firmware flash verification failed."
+		fi
+	fi
+
 	# Remove the Application processor reset
 	# TODO(crosbug.com/p/30738): we cannot rely on servo_VARS to restore it
 	if $(servo_has_warm_reset); then
