flash_ec: add support for ITE UART programming
Add a new chip type "ite_uart" for programming ITE EC chips using a UART
interface.

BUG=b:328620169
TEST=Run "flash_ec --chip ite_uart" against brox using servo_micro

Change-Id: I1e97b4c0c6fed8dfa65e04de1b339fcb519a545c

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -434,7 +434,8 @@ esac
 
 case "${CHIP}" in
 	"stm32"|"npcx_spi"|"npcx_int_spi"|"it83xx"|"ite_i2c"|"npcx_uut"|"ite_spi"| \
-			"ite_spi_ccd_i2c"|"it8xxx2"|"mchp_int_spi")
+			"ite_spi_ccd_i2c"|"ite_uart"|"flash_ite_uart_3m"| \
+			"it8xxx2"|"mchp_int_spi")
 		;;
 	*)
 		if [[ -n "${FLAGS_read}" ]]; then
@@ -1580,6 +1581,80 @@ function flash_it83xx() {
 	print_or_run "${ITEFLASH_ARGS[@]}" || die "${ERROR_MSG}"
 }
 
+function flash_ite_uart_common() {
+	local BAUDRATE=$1
+	local ITECOMDBGR_BIN
+	local TOOL_PATH="${EC_DIR}/build/host/util:${PATH}"
+	local EC_UART_PREFIX
+	TEMP_DIR="$(mktemp -d --suffix="${TEMP_SUFFIX}")"
+	# DELETE_LIST+=("${TEMP_DIR}")
+
+	EC_UART_PREFIX="$(servo_ec_uart_prefix)"
+
+	info "Programming EC firmware using ITE UART interface"
+
+	ITECOMDBGR_BIN=$(PATH="${TOOL_PATH}" which itecomdbgr)
+	EC_UART="$(servo_ec_uart)"
+
+	info "ITE tool = ${ITECOMDBGR_BIN}"
+	info "EC UART = ${EC_UART}"
+
+	servo_save_add "${EC_UART_PREFIX}_baudrate"
+	servo_save_add "${EC_UART_PREFIX}_parity"
+
+	claim_pty "${EC_UART}"
+
+	# UART programming requires even partity
+	info "Using ${BAUDRATE} baudrate"
+	dut_control_or_die "${EC_UART_PREFIX}_baudrate:${BAUDRATE}"
+	dut_control_or_die "${EC_UART_PREFIX}_parity:even"
+
+	if servo_is_ccd ; then
+		servo_save_add "${EC_UART_PREFIX}_bitbang_en"
+		dut_control "${EC_UART_PREFIX}_bitbang_en:on"
+	fi
+
+	# Build the iteflash command line.
+	local ITEFLASH_ARGS=( "sudo" "--" "${ITECOMDBGR_BIN}" )
+	ITEFLASH_ARGS+=( "-d" "${EC_UART}" )
+	ITEFLASH_ARGS+=( "-b" "${BAUDRATE}" )
+
+	if [[ "${FLAGS_no_preserve}" == "${FLAGS_FALSE}" && \
+	      -z "${FLAGS_read}" ]]; then
+		local IMG_CPY
+
+		IMG_CPY="${TEMP_DIR}/ec.new.cpy.bin"
+		cat "${IMG}" > "${IMG_CPY}"
+		IMG="${IMG_CPY}"
+		preserve_sections "ite_uart" "${IMG}" "${TEMP_DIR}"    \
+			"${ITEFLASH_ARGS[@]}" || die "${MSG_PROGRAM_FAIL}"
+	fi
+
+	if [[ -n "${FLAGS_read}" ]]; then
+		ITEFLASH_ARGS+=( "-r" "${FLAGS_read}" )
+	else
+		ITEFLASH_ARGS+=( "-f" "${IMG}" )
+	fi
+
+	if [[ "${FLAGS_verify}" == "${FLAGS_FALSE}" ]]; then
+		ITEFLASH_ARGS+=( "-n" )
+	fi
+
+	print_or_run "${ITEFLASH_ARGS[@]}" || die "${ERROR_MSG}"
+}
+
+function flash_ite_uart() {
+	flash_ite_uart_common 115200
+}
+function flash_ite_uart_3m() {
+	if servo_is_ccd ; then
+		# Servo only supports 115200
+		flash_ite_uart_common 115200
+	else
+		flash_ite_uart_common 3000000
+	fi
+}
+
 # Alias for flashing ITE chips over I2C from all servo types.
 function flash_ite_i2c() {
         flash_it83xx
@@ -2076,6 +2151,20 @@ function read_chip_partially() {
 		servo_ec_hard_reset_or_die
 		# ITE DFU mode must be re-enabled after each operation
 		ite_dfu_mode
+	elif [ "${CHIP_TYPE}" == "ite_uart" ]; then
+		local UUT_CUR_FMAP_RD
+
+		UUT_CUR_FMAP_RD=( "${CHIP_CMD_PREFIX[@]}" \
+			"-r" "${FILE_PATH}" \
+			"-R" "${OFFSET}" "${SIZE}")
+
+		# UART based reads are quite slow, over 3 minutes for the full
+		# image.
+		info "${UUT_CUR_FMAP_RD[@]}"
+
+		print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+			"${UUT_CUR_FMAP_RD[@]}" || die "${MSG_READ_FAIL}"
+
 	elif [ "${CHIP_TYPE}" == "spi" ]; then
 		local FLASHROM_FMAP_RD
 
@@ -2114,6 +2203,11 @@ function read_chip() {
 		servo_ec_hard_reset_or_die
 		# ITE DFU mode must be re-enabled after each operation
 		ite_dfu_mode
+	elif [ "${CHIP_TYPE}" == "ite_uart" ]; then
+		UUT_CUR_RD=( "${CHIP_CMD_PREFIX[@]}" "-r" "${FILE_PATH}" )
+		print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+					"${UUT_CUR_RD[@]}" || die "${MSG_READ_FAIL}"
+
 	elif [ "${CHIP_TYPE}" == "spi" ]; then
 		FLASHROM_RD=( "sudo" "${CHIP_CMD_PREFIX[@]}" "--read=${FILE_PATH}" )
 		print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
