flash_ec: support realtek ec
Support servo_v4p1 via flash_ec.
However, the servo_micro still not working.

BUG=b:359582898
TEST=use servo_v4p1 and flash_ec to update realtek ec.

Change-Id: Ib048617ba7e2418f6087d8a5a488f0147fbc4dff

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -448,9 +448,9 @@ case "${BOARD}" in
 esac
 
 case "${CHIP}" in
-	"stm32"|"npcx_spi"|"npcx_int_spi"|"it83xx"|"ite_i2c"|"npcx_uut"|"ite_spi"| \
-			"ite_spi_ccd_i2c"|"ite_spi_ccd_uart"|"ite_uart"|"ite_uart_3m"| \
-			"it8xxx2"|"mchp_int_spi")
+	"stm32"|"npcx_spi"|"npcx_int_spi"|"it83xx"|"ite_i2c"|"npcx_uut"|"rtk_uart"| \
+			"ite_spi"|"ite_spi_ccd_i2c"|"ite_spi_ccd_uart"|"ite_uart"| \
+			"ite_uart_3m"|"it8xxx2"|"mchp_int_spi")
 		;;
 	*)
 		if [[ -n "${FLAGS_read}" ]]; then
@@ -1730,6 +1730,175 @@ function flash_npcx_jtag() {
 	ec_reset
 
 	flash_openocd
+}
+
+
+function flash_rtk_uart() {
+	local RTK_UUT
+	local EC_UART
+	local TEMP_SUFFIX
+	local TEMP_DIR
+	local TOOL_PATH="${EC_DIR}/build/host/util:${PATH}"
+
+	RTK_UUT=$(PATH="${TOOL_PATH}" which rtkupdate)
+	EC_UART="$(servo_ec_uart)"
+	TEMP_SUFFIX=".$(basename "${SCRIPT}").${CHIP}.$$"
+	TEMP_DIR="$(mktemp -d --suffix="${TEMP_SUFFIX}")"
+	DELETE_LIST+=("${TEMP_DIR}")
+
+	# Look for rts5915_flash_upload.bin in multiple directories, starting with
+	# the same path as the EC binary.
+	local MON=""
+	for dir in \
+		"$(dirname "${IMG}")" \
+		"${EC_DIR}/build/zephyr/${BOARD}/output" \
+		"${EC_DIR}/build/zephyr/${BOARD}/build-rw" \
+		"${EC_DIR}/build/zephyr/${BOARD}/build-ro" \
+		"$(dirname "${LOCAL_BUILD}")" \
+		"$(dirname "${EMERGE_BUILD}")" \
+		"/usr/share/ec-devutils" ;
+	do
+		if [ -f "${dir}/rts5915_flash_upload.bin" ] ; then
+			MON="${dir}/rts5915_flash_upload.bin"
+			break
+		fi
+	done
+	if [ -z "${MON}" ] ; then
+		echo "Failed to find rts5915_flash_upload.bin"
+		exit 1
+	fi
+	info "Using RTK image : ${MON}"
+
+	# The start address to restore monitor firmware binary
+	local MON_ADDR="0x00000000"
+
+	if [ ! -x "${RTK_UUT}" ]; then
+		die "no RTK UART Update Tool found."
+	fi
+
+	info "Using: RTK UART Update Tool"
+	info "${MCU} UART pty : ${EC_UART}"
+	claim_pty "${EC_UART}"
+
+	if [[ "${SERVO_TYPE}" =~ "ccd_cr50" ]] ; then
+		# Ti50 does not yet support ccd_keepalive option which
+		# requires ccdstate command on the GSC console.
+		# TODO(b/161483597) remove the check when Ti50 CCD is on par.
+		servo_save_add ccd_keepalive_en
+		dut_control ccd_keepalive_en:on
+	fi
+
+	# Don't let the EC come out of reset after H1 reset
+	dut_control gsc_ec_reset:on
+	sleep 0.1
+	# Force the EC to boot in UART update mode
+	ec_enable_boot0 "uut"
+	sleep 0.1
+
+	dut-control gsc_ec_reset:off
+
+	# Have to wait a bit for EC boot-up
+	sleep 1
+	# Ensure normal UART operation
+	ec_disable_boot0 "uut"
+	sleep 0.1
+
+	# Remove the prefix "/dev/" because uartupdatetool will add it.
+	local UUT_ARGS=( "--port=${EC_UART#/dev/}" " --baudrate=115200" )
+	local IMG_READ="${FLAGS_read}"
+
+	local monitor_res=0
+	local wp_res=0
+
+
+# Write Protect
+	local UUT_WP=(
+			"${RTK_UUT}"  \
+			"--method wp" \
+			"--spi_start ${MON_ADDR}"  \
+			"--file ${MON}" \
+			"--uart_device ${EC_UART}" \
+			"--spi_offset 0x0")
+
+	print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+		"${UUT_WP[@]}" || wp_res=$?
+
+	if [[ ${wp_res} != 0 ]]; then
+		die "Failed to load monitor binary."
+	fi
+
+# Load monitor binary
+	info "Loading monitor binary."
+	local UUT_MON=(
+			"${RTK_UUT}"  \
+			"--method frame" \
+			"--spi_start ${MON_ADDR}"  \
+			"--file ${MON}" \
+			"--uart_device ${EC_UART}" \
+			"--spi_offset 0x0")
+
+	print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+			"${UUT_MON[@]}" || monitor_res=$?
+
+	if [[ ${monitor_res} != 0 ]]; then
+		die "Failed to load monitor binary."
+	fi
+
+# Program EC image.
+	if [[ -z "${IMG_READ}" ]]; then
+		if [[ "${FLAGS_no_preserve}" == "${FLAGS_FALSE}" ]]; then
+			local IMG_CPY
+
+			IMG_CPY="${TEMP_DIR}/ec.new.cpy.bin"
+			cat "${IMG}" > "${IMG_CPY}"
+			IMG="${IMG_CPY}"
+			preserve_sections "${CHIP}" "${IMG}" "${TEMP_DIR}"    \
+				"${RTK_UUT}" "${UUT_ARGS[@]}" || die "${MSG_PROGRAM_FAIL}"
+		fi
+
+		info "Programming EC firmware image."
+		local UUT_WR=(
+				"${RTK_UUT}" \
+				"--method flash" \
+				"--spi_start ${MON_ADDR}" \
+				"--file ${IMG}" \
+				"--uart_device ${EC_UART}" \
+				"--spi_offset 0x0")
+
+		print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+			"${UUT_WR[@]}" || die "${MSG_PROGRAM_FAIL}"
+
+		# If it is a program-verify request, then make a temporary
+		# directory to store the image.
+		if [[ "${FLAGS_verify}" == "${FLAGS_TRUE}" ]]; then
+			IMG_READ="${TEMP_DIR}/ec.read.bin"
+		fi
+	fi
+
+	# Read EC image.
+	if [[ -n "${IMG_READ}" ]]; then
+		info "Reading EC firmware image."
+
+		local UUT_RD=(
+				"${RTK_UUT}" \
+				"--method read_bin" \
+				"--spi_start ${MON_ADDR}" \
+				"--file ${IMG_READ}" \
+				"--uart_device ${EC_UART}" \
+				"--spi_offset ${IMG_SIZE}")
+
+		print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+			"${UUT_RD[@]}" || die "${MSG_READ_FAIL}"
+	fi
+
+	# Verify the flash by comparing the source image to the read image,
+	# only if it was a flash write request.
+	if [[ -z "${FLAGS_read}" && "${FLAGS_verify}" == "${FLAGS_TRUE}" ]]; then
+		info "Verifying EC firmware image."
+
+		print_or_run cmp -s -n "${IMG_SIZE}" "${IMG}" "${IMG_READ}" \
+			|| die "${MSG_VERIFY_FAIL}"
+	fi
 }
 
 function flash_npcx_uut() {
