[Do not merge]flash_ec: support realtek ec
Support servo_v4p1 via flash_ec.
However, the servo_micro still not wirking.

BUG=b:359582898
TEST=use servo_v4p1 and flash_ec to update realtek ec.

Change-Id: Ifd215d478cb5fdb3f77a578fadd5684da40fc4c3

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -130,6 +130,11 @@ BOARDS_NPCX_INT_SPI_UUT=(
 	ptlrvp_npcx
 )
 
+BOARDS_RTK_INT_SPI_UUT=(
+	servo_v4p1
+	servo_micro
+)
+
 BOARDS_SPI_1800MV=(
 	coral
 	reef
@@ -378,6 +383,10 @@ if in_array "${BOARDS_NPCX_INT_SPI_UUT[@]}" "${BOARD}"; then
 	SUPPORTED_CHIPS+=("npcx_uut")
 fi
 
+if in_array "${BOARDS_RTK_INT_SPI_UUT[@]}" "${BOARD}"; then
+	SUPPORTED_CHIPS+=("rtk_uut")
+fi
+
 if in_array "${BOARDS_IT83XX[@]}" "${BOARD}"; then
 	SUPPORTED_CHIPS+=("it83xx")
 fi
@@ -449,7 +458,7 @@ case "${BOARD}" in
 esac
 
 case "${CHIP}" in
-	"stm32"|"npcx_spi"|"npcx_int_spi"|"it83xx"|"ite_i2c"|"npcx_uut"|"ite_spi"| \
+	"stm32"|"npcx_spi"|"npcx_int_spi"|"it83xx"|"ite_i2c"|"npcx_uut"|"rtk_uut"|"ite_spi"| \
 			"ite_spi_ccd_i2c"|"ite_spi_ccd_uart"|"ite_uart"|"ite_uart_3m"| \
 			"it8xxx2"|"mchp_int_spi")
 		;;
@@ -571,6 +580,7 @@ ec_reset() {
 	fi
 
 	if [[ -n "${stype}" ]]; then
+		echo "hard reset"
 		eval "${stype}_${MCU}_hard_reset"
 	fi
 }
@@ -608,6 +618,7 @@ servo_micro_ec_boot0() {
 		dut_control "tp1:$1"
 		dut_control "servo_micro_ec_boot_mode_$2:$1"
 	else
+		info "ec_boot_mode:$1"
 		info "Servo micro $2 mode: $1 (using FW_UP_L)"
 		dut_control "ec_boot_mode:$1"
 	fi
@@ -650,12 +661,16 @@ ec_switch_boot0() {
 		dut_control prog_en:yes
 	fi
 	if servo_is_ccd ; then
+		echo "ccd"
 		stype=ccd
 	elif [[ "${SERVO_TYPE}" =~ "servo_micro" ]] ; then
+		echo "servo_micro"
 		stype=servo_micro
 	elif [[ "${SERVO_TYPE}" =~ "servo" ]] ; then
+		echo "servo"
 		stype=servo
 	else
+		echo "else"
 		stype=${SERVO_TYPE}
 	fi
 	eval "${stype}_${MCU}_boot0" "${on_value}" "$2"
@@ -1731,6 +1746,169 @@ function flash_npcx_jtag() {
 	ec_reset
 
 	flash_openocd
+}
+
+
+function flash_rtk_uut() {
+	local RTK_UUT
+	local EC_UART
+	local TEMP_SUFFIX
+	local TEMP_DIR
+	#local TOOL_PATH="${EC_DIR}/build/zephyr/${BOARD}/util/"
+	local TOOL_PATH="/mnt/host/source/src/platform/ec/build/zephyr/brtk/util/v00_retry"
+	set +e
+	RTK_UUT=${TOOL_PATH}
+	set -e
+	EC_UART="$(servo_ec_uart)"
+	TEMP_SUFFIX=".$(basename "${SCRIPT}").${CHIP}.$$"
+	TEMP_DIR="$(mktemp -d --suffix="${TEMP_SUFFIX}")"
+	DELETE_LIST+=("${TEMP_DIR}")
+
+	# Look for rts5915_flash_upload_13v2.bin in multiple directories, starting with
+	# the same path as the EC binary.
+	local MON=""
+	for dir in \
+		"$(dirname "${IMG}")" \
+		"${EC_DIR}/build/zephyr/${BOARD}/output" \
+		"$(dirname "${LOCAL_BUILD}")" \
+		"$(dirname "${EMERGE_BUILD}")" \
+		"/usr/share/ec-devutils" ;
+	do
+		if [ -f "${dir}/rts5915_flash_upload_13v2.bin" ] ; then
+			MON="${dir}/rts5915_flash_upload_13v2.bin"
+			break
+		fi
+	done
+	if [ -z "${MON}" ] ; then
+		echo "Failed to find rts5915_flash_upload_13v2.bin"
+		exit 1
+	fi
+	info "Using RTK image : ${MON}"
+
+	# The start address to restore monitor firmware binary
+	local MON_ADDR="0x00000000"
+
+	if [ ! -x "${RTK_UUT}" ]; then
+		die "no RTK UART Update Tool found."
+	fi
+
+	info "Using: RTK UART Update Tool"
+	info "${MCU} UART pty : ${EC_UART}"
+	claim_pty "${EC_UART}"
+
+	if [[ "${SERVO_TYPE}" =~ "ccd_cr50" ]] ; then
+		echo "ccd"
+		# Ti50 does not yet support ccd_keepalive option which
+		# requires ccdstate command on the GSC console.
+		# TODO(b/161483597) remove the check when Ti50 CCD is on par.
+		servo_save_add ccd_keepalive_en
+		dut_control ccd_keepalive_en:on
+	fi
+
+	# C2D2 does not use waits and has to ensure that the EC does not come
+	# out of reset after using a H1-level reset
+	if [[ "${SERVO_TYPE}" =~ "c2d2" ]] ; then
+		echo "c2d2"
+		c2d2_wait_for_h1_power_on_or_reset
+
+		# Don't let the EC come out of reset after H1 reset
+		dut_control gsc_ec_reset:on
+
+		# Force the EC to boot in UART update mode coming out of reset
+		ec_enable_boot0 "uut"
+		dut_control gsc_ec_reset:off
+
+		# Ensure normal UART operation
+		ec_disable_boot0 "uut"
+	else
+		echo "good"
+		# Don't let the EC come out of reset after H1 reset
+		dut_control gsc_ec_reset:on
+		sleep 0.1
+		# Force the EC to boot in UART update mode
+		ec_enable_boot0 "uut"
+		sleep 0.1
+		
+		dut-control gsc_ec_reset:off
+
+
+		# Have to wait a bit for EC boot-up
+		sleep 15
+		# Ensure normal UART operation
+		ec_disable_boot0 "uut"
+		sleep 0.1
+	fi
+
+	# Remove the prefix "/dev/" because uartupdatetool will add it.
+	local UUT_ARGS=( "--port=${EC_UART#/dev/}" " --baudrate=115200" )
+	local IMG_READ="${FLAGS_read}"
+
+	# Program EC image.
+	if [[ -z "${IMG_READ}" ]]; then
+		info "Loading monitor binary."
+		local UUT_MON=( "${RTK_UUT}" "frame" "${MON_ADDR}"  \
+				"${MON}" \
+				"${EC_UART}" )
+
+		# Load monitor binary to address 0x200C3020
+		for ((i=0; i<10; i++)); do
+			monitor_res=0
+			print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+				"${UUT_MON[@]}" || monitor_res=$?
+			echo $monitor_res
+			if [ $monitor_res -eq 0 ]; then
+				break
+			fi
+		done
+
+		if [[ ${monitor_res} != 0 ]]; then
+
+			die "Failed to load monitor binary."
+		fi
+
+		# if [[ "${FLAGS_no_preserve}" == "${FLAGS_FALSE}" ]]; then
+		# 	local IMG_CPY
+
+		# 	IMG_CPY="${TEMP_DIR}/ec.new.cpy.bin"
+		# 	cat "${IMG}" > "${IMG_CPY}"
+		# 	IMG="${IMG_CPY}"
+		# 	preserve_sections "${CHIP}" "${IMG}" "${TEMP_DIR}"    \
+		# 		"${RTK_UUT}" "${UUT_ARGS[@]}" || die "${MSG_PROGRAM_FAIL}"
+		# fi
+
+		info "Programming EC firmware image."
+		local UUT_WR=( "${RTK_UUT}" "flash" "${MON_ADDR}"  \
+				"${IMG}" \
+				"${EC_UART}" )
+		print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+			"${UUT_WR[@]}" || die "${MSG_PROGRAM_FAIL}"
+
+		# # If it is a program-verify request, then make a temporary
+		# # directory to store the image.
+		# if [[ "${FLAGS_verify}" == "${FLAGS_TRUE}" ]]; then
+		# 	IMG_READ="${TEMP_DIR}/ec.read.bin"
+		# fi
+	fi
+
+	# # Read EC image.
+	# if [[ -n "${IMG_READ}" ]]; then
+	# 	info "Reading EC firmware image."
+
+	# 	local UUT_RD=( "${RTK_UUT}" "${UUT_ARGS[@]}"   \
+	# 		      "--read-flash" "--file=${IMG_READ}" )
+
+	# 	print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+	# 		"${UUT_RD[@]}" || die "${MSG_READ_FAIL}"
+	# fi
+
+	# # Verify the flash by comparing the source image to the read image,
+	# # only if it was a flash write request.
+	# if [[ -z "${FLAGS_read}" && "${FLAGS_verify}" == "${FLAGS_TRUE}" ]]; then
+	# 	info "Verifying EC firmware image."
+
+	# 	print_or_run cmp -s -n "${IMG_SIZE}" "${IMG}" "${IMG_READ}" \
+	# 		|| die "${MSG_VERIFY_FAIL}"
+	# fi
 }
 
 function flash_npcx_uut() {
