util: Refactor flash_fp_mcu to use main function
https://google.github.io/styleguide/shellguide.html#s7.8-main

BRANCH=none
BUG=none
TEST=# dut1 is a dratini device
     scp util/flash_fp_mcu dut1:/usr/local/bin/flash_fp_mcu
     ssh dut1 flash_fp_mcu --hello; echo "Status $?"
     # Should succeed
     ssh dut1 flash_fp_mcu '/opt/google/biod/fw/bloonchipper*'; echo "Status $?"
     # Should succeed
     ssh dut1 flash_fp_mcu; echo "Status $?"
     # Should error out about no filename

Signed-off-by: Craig Hesling <hesling@chromium.org>
Change-Id: I2f5f0c05e6c0a83a67948c5f914470b08a5d2c56

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -25,16 +25,6 @@ FLAGS_HELP="Usage: ${0} [flags] ec.bin"
 FLAGS "${@}" || exit 1
 eval set -- "${FLAGS_ARGV}"
 
-if [[ "$#" -eq 0 ]] && [[ "${FLAGS_hello}" -eq "${FLAGS_FALSE}" ]]; then
-  echo "Missing filename"
-  flags_help
-  exit 1
-fi
-
-# print out canonical path to differentiate between /usr/local/bin and
-# /usr/bin installs
-readlink -f "$0"
-
 readonly CROS_EC_SPI_MODALIAS_STR="of:NcrfpTCgoogle,cros-ec-spi"
 
 readonly CROS_EC_UART_MODALIAS_STR="of:NcrfpTCgoogle,cros-ec-uart"
@@ -497,36 +487,50 @@ config_guybrush() {
   readonly GPIO_PWREN=-1
 }
 
-# The "platform name" corresponds to the underlying board (reference design)
-# that we're running on (not the FPMCU or sensor). At the moment all of the
-# reference designs use the same GPIOs. If for some reason a design differs in
-# the future, we will want to add a nested check in the config_<platform_name>
-# function. Doing it in this manner allows us to reduce the number of
-# configurations that we have to maintain (and reduces the amount of testing
-# if we're only updating a specific config_<platform_name>).
-if ! PLATFORM_NAME="$(get_platform_name)"; then
-  echo "Failed to get platform name"
-  exit 1
-fi
-readonly PLATFORM_NAME
+main() {
+  if [[ "$#" -eq 0 ]] && [[ "${FLAGS_hello}" -eq "${FLAGS_FALSE}" ]]; then
+    echo "Missing filename"
+    flags_help
+    exit 1
+  fi
 
-echo "Using config for ${PLATFORM_NAME}"
+  # print out canonical path to differentiate between /usr/local/bin and
+  # /usr/bin installs
+  readlink -f "$0"
 
-# Check that the config function exists
-if [[ "$(type -t "config_${PLATFORM_NAME}")" != "function" ]]; then
-  echo "No config for platform ${PLATFORM_NAME}"
-  exit 1
-fi
+  # The "platform name" corresponds to the underlying board (reference design)
+  # that we're running on (not the FPMCU or sensor). At the moment all of the
+  # reference designs use the same GPIOs. If for some reason a design differs in
+  # the future, we will want to add a nested check in the config_<platform_name>
+  # function. Doing it in this manner allows us to reduce the number of
+  # configurations that we have to maintain (and reduces the amount of testing
+  # if we're only updating a specific config_<platform_name>).
+  if ! PLATFORM_NAME="$(get_platform_name)"; then
+    echo "Failed to get platform name"
+    exit 1
+  fi
+  readonly PLATFORM_NAME
 
-if ! "config_${PLATFORM_NAME}"; then
-  echo "Configuration failed for platform ${PLATFORM_NAME}"
-  exit 1
-fi
+  echo "Using config for ${PLATFORM_NAME}"
 
-flash_fp_mcu_stm32 \
-  "${TRANSPORT}"   \
-  "${DEVICE}"      \
-  "${GPIO_NRST}"   \
-  "${GPIO_BOOT0}"  \
-  "${GPIO_PWREN}"  \
-  "${1}"
+  # Check that the config function exists
+  if [[ "$(type -t "config_${PLATFORM_NAME}")" != "function" ]]; then
+    echo "No config for platform ${PLATFORM_NAME}"
+    exit 1
+  fi
+
+  if ! "config_${PLATFORM_NAME}"; then
+    echo "Configuration failed for platform ${PLATFORM_NAME}"
+    exit 1
+  fi
+
+  flash_fp_mcu_stm32 \
+    "${TRANSPORT}"   \
+    "${DEVICE}"      \
+    "${GPIO_NRST}"   \
+    "${GPIO_BOOT0}"  \
+    "${GPIO_PWREN}"  \
+    "${1}"
+}
+
+main "$@"
