Fix the ec flash programming script to properly handle errors
When a nonexisting file is specified as the EC image, the ec flash
programming script reports the error, but continues running and
returns zero status (success) after completion.

With this change the exit status on some errors gets communicated to
the caller.

The openocd script is edited to drop the unused parameter of the
flash_lm4() function.

BRANCH=none
BUG=chrome-os-partner:15610
TEST=manual
   . run flash_ec with nonexisting or nonreadable file as a parameter,
     observe it to report proper return status. Run it with a proper
     image file name and observe it succeed.
   . run the command again, while the device is being programmed enter
     'ctl-c', observe programming stepped but the 'Restoring servo
     settings..." message still showing up.

Change-Id: Iac0b233fe579b0d5a84cf5a9acf85ed8bf10422e
Signed-off-by: Vadim Bendebury <vbendeb@chromium.org>

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -14,12 +14,24 @@ DEFINE_string image "" \
 	"Full pathname of the EC firmware image to flash."
 DEFINE_boolean ro "${FLAGS_FALSE}" \
 	"Write only the read-only partition"
+DEFINE_string offset "0" \
+	"Offset where to program the image from."
 
 # Parse command line
 FLAGS_HELP="usage: $0 [flags]"
 FLAGS "$@" || exit 1
 eval set -- "${FLAGS_ARGV}"
 check_flags_only_and_allow_null_arg "$@" && set --
+
+set -e
+
+cleanup() {
+	if [ -n "${save}" ]; then
+		info "Restoring servo settings..."
+		servo_restore "$save"
+	fi
+}
+trap cleanup EXIT
 
 BOARD=${FLAGS_board}
 BOARD_ROOT=/build/${BOARD}
@@ -104,15 +116,15 @@ function flash_daisy() {
 }
 
 function flash_link() {
-	IMG_SIZE=262144
 	OCD_CFG="servo_v2_slower.cfg"
 	OCD_PATH="${SRC_ROOT}/platform/ec/chip/lm4/openocd"
-	OCD_CMDS="init ; flash_lm4 ${IMG} 0 262144 ; exit"
+	OCD_CMDS="init ; flash_lm4 ${IMG} ${FLAGS_offset}; shutdown;"
 
 	dut_control jtag_buf_on_flex_en:on
 	dut_control jtag_buf_en:on
 
-	sudo openocd -s "${OCD_PATH}" -f "${OCD_CFG}" -c "${OCD_CMDS}"
+	sudo openocd -s "${OCD_PATH}" -f "${OCD_CFG}" -c "${OCD_CMDS}" || \
+          die "Failed to program ${IMG}"
 }
 
 IMG="$(ec_image)"
@@ -130,9 +142,6 @@ case "${BOARD}" in
 esac
 
 info "Flashing done."
-
-# Restore servo settings
-servo_restore "$save"
 
 # reset the EC
 dut_control cold_reset:on
