cbi: flash: Preserve CBI section while flashing using flash_ec
BUG=b:267804768
TEST=flashed on Rex, saw the new EC image getting updated

Change-Id: I91d71ab84039254844d217a1eb9c01697cea72ce

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -1473,9 +1473,16 @@ function flash_npcx_jtag() {
 function flash_npcx_uut() {
 	local NPCX_UUT
 	local EC_UART
+	local TEMP_SUFFIX
+	local TEMP_DIR
+	local CUR_IMG
+	local PRESERVE_STATUS
 	local TOOL_PATH="${EC_DIR}/build/${BOARD}/util:${PATH}"
 	NPCX_UUT=$(PATH="${TOOL_PATH}" which uartupdatetool)
 	EC_UART="$(servo_ec_uart)"
+	TEMP_SUFFIX=".$(basename "${SCRIPT}").${CHIP}.$$"
+	TEMP_DIR="$(mktemp -d --suffix="${TEMP_SUFFIX}")"
+	DELETE_LIST+=("${TEMP_DIR}")
 
 	# Look for npcx_monitor.bin in multiple directories, starting with
 	# the same path as the EC binary.
@@ -1580,6 +1587,20 @@ function flash_npcx_uut() {
 			die "Failed to load monitor binary."
 		fi
 
+		PRESERVE_STATUS=$(is_preservation_needed "${IMG}" "${TEMP_DIR}")
+		if [[ "${PRESERVE_STATUS}" == "1" ]]; then
+			info "Reading current EC firmware image."
+			CUR_IMG="${TEMP_DIR}/ec.cur.bin"
+			local UUT_CUR_RD=( "${NPCX_UUT}" "${UUT_ARGS[@]}"   \
+						"--read-flash" "--file=${CUR_IMG}" )
+			echo "${UUT_CUR_RD[*]}"
+			print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+				"${UUT_CUR_RD[@]}" || die "${MSG_READ_FAIL}"
+
+			preserve_sections "${CUR_IMG}" "${IMG}" "${TEMP_DIR}"
+		elif [[ "${PRESERVE_STATUS}" == "0" ]]; then
+			info "Not preserving any EC section."
+		fi
 
 		info "Programming EC firmware image."
 		local UUT_WR=( "${NPCX_UUT}" "${UUT_ARGS[@]}"      \
@@ -1594,13 +1615,7 @@ function flash_npcx_uut() {
 		# If it is a program-verify request, then make a temporary
 		# directory to store the image.
 		if [[ "${FLAGS_verify}" == "${FLAGS_TRUE}" ]]; then
-			local TEMP_SUFFIX
-			local TEMP_DIR
-			TEMP_SUFFIX=".$(basename "${SCRIPT}").${CHIP}.$$"
-			TEMP_DIR="$(mktemp -d --suffix="${TEMP_SUFFIX}")"
-
 			IMG_READ="${TEMP_DIR}/ec.read.bin"
-			DELETE_LIST+=( "${TEMP_DIR}" )
 		fi
 	fi
 
@@ -1701,6 +1716,58 @@ fi
 if [ "${NEED_SERVO}" != "no" ] ; then
 	servo_save
 fi
+
+function is_preservation_needed() {
+	local IMG
+	local TEMP_DIR
+	local CUR_DIR
+	local PRESERVE_STATUS
+
+	IMG=${1:?"missing arg 1: EC image path"}
+	TEMP_DIR=${2:?"missing arg 2: Temp directory path"}
+	CUR_DIR=$(pwd)
+
+	PRESERVE_STATUS=$(
+		local SUBSHELL_OUTPUT
+
+		cd "${TEMP_DIR}"
+		if dump_fmap "${CUR_DIR}"/"${IMG}" -e | grep -q ' preserve'; then
+			SUBSHELL_OUTPUT=1
+		else
+			SUBSHELL_OUTPUT=0
+		fi
+		echo "${SUBSHELL_OUTPUT}"
+	)
+	echo "${PRESERVE_STATUS}"
+}
+
+function preserve_sections() {
+	local CUR_IMG
+	local NEW_IMG
+	local TEMP_DIR
+	local CUR_DIR
+
+	CUR_IMG=${1:?"missing arg 1: Cur EC image path"}
+	NEW_IMG=${2:?"missing arg 2: New EC image path"}
+	TEMP_DIR=${3:?"missing arg 3: Temp directory path"}
+	CUR_DIR=$(pwd)
+
+	(
+		local DUMP_FMAP
+
+		cd "${TEMP_DIR}"
+		DUMP_FMAP=$(dump_fmap "${CUR_DIR}"/"${IMG}" -e | grep ' preserve' | cut \
+			-f1 -d' ')
+		while read -r line
+		do
+			info "Preserving ${line} section on EC chip"
+			local SEC_IMG="${TEMP_DIR}/ec.cur.${line}.bin"
+
+			cbfstool "${CUR_IMG}" read -r "${line}" -f "${SEC_IMG}"
+			cbfstool "${CUR_DIR}"/"${NEW_IMG}" write -r "${line}" -f "${SEC_IMG}"
+		done <<< "${DUMP_FMAP}"
+	)
+}
 
 info "Flashing chip ${CHIP}."
 flash_"${CHIP}"
