util/flash_fp_mcu: Make get_platform_name work on Android
BUG=b:381902143
TEST=CQ

Change-Id: I9576b7488169723d5a523e0176889fcad85535a1

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -294,25 +294,40 @@ lsbval() {
 get_platform_name() {
   local platform_name
 
-  # We used to use "cros_config /identity platform-name", but that is specific
-  # to mosys and does not actually provide the board name in all cases.
-  # cros_config intentionally does not provide a way to get the board
-  # name: b/156650654.
+  case "$(os)" in
+    "chromeos")
+      # We used to use "cros_config /identity platform-name", but that is specific
+      # to mosys and does not actually provide the board name in all cases.
+      # cros_config intentionally does not provide a way to get the board
+      # name: b/156650654.
 
-  # If there was a way to get the board name from cros_config, it's possible
-  # that it could fail in the following cases:
-  #
-  # 1) We're running on a non-unibuild device (the only one with FP is nocturne)
-  # 2) We're running on a proto device during bringup and the cros_config
-  #    settings haven't yet been setup.
-  #
-  # In all cases we can fall back to /etc/lsb-release. It's not recommended
-  # to do this, but we don't have any other options in this case.
-  echo "Getting platform name from /etc/lsb-release." 1>&2
-  platform_name="$(lsbval "CHROMEOS_RELEASE_BOARD")"
-  if [[ -z "${platform_name}" ]]; then
-    return 1
-  fi
+      # If there was a way to get the board name from cros_config, it's possible
+      # that it could fail in the following cases:
+      #
+      # 1) We're running on a non-unibuild device (the only one with FP is nocturne)
+      # 2) We're running on a proto device during bringup and the cros_config
+      #    settings haven't yet been setup.
+      #
+      # In all cases we can fall back to /etc/lsb-release. It's not recommended
+      # to do this, but we don't have any other options in this case.
+      echo "Getting platform name from /etc/lsb-release." 1>&2
+      platform_name="$(lsbval "CHROMEOS_RELEASE_BOARD")"
+      if [[ -z "${platform_name}" ]]; then
+        return 1
+      fi
+      ;;
+    "android")
+      echo "Getting platform name from ro.product.device." 1>&2
+      platform_name="$(getprop ro.product.device 2>/dev/null)"
+      if [[ -z "${platform_name}" ]]; then
+        return 1
+      fi
+      ;;
+    *)
+      echo "Unsupported operating system" 1>&2
+      return 1
+      ;;
+  esac
 
   echo "${platform_name}"
 }
