ish gpio: enable gpio console commands
BUG=none
BRANCH=none
TEST=Tested on Soraka board with ISH, gpioget/gpioset is working.

Change-Id: Iac19a7548b89f6537ecd8f327e8d4e14ef779939
Signed-off-by: li feng <li1.feng@intel.com>

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -60,7 +60,6 @@ BOARDS_STM32=(
 	chell_pd
 	coffeecake
 	elm
-	eve_fp
 	glados_pd
 	hammer
 	jerry
@@ -109,6 +108,9 @@ BOARDS_NPCX_7M6X_JTAG=(
 	npcx7_evb
 )
 
+BOARDS_NPCX_7M7X_JTAG=(
+)
+
 BOARDS_NPCX_SPI=(
 	coral
 	eve
@@ -116,6 +118,8 @@ BOARDS_NPCX_SPI=(
 	glkrvp
 	gru
 	kevin
+        lux
+	nami
 	nautilus
 	poppy
 	reef
@@ -156,6 +160,7 @@ BOARDS_RAIDEN=(
 	fizz
 	gru
 	kevin
+	nami
 	nautilus
 	poppy
 	reef
@@ -240,6 +245,8 @@ elif $(in_array "${BOARDS_NPCX_5M6G_JTAG[@]}" "${BOARD}"); then
 	CHIP="npcx_5m6g_jtag"
 elif $(in_array "${BOARDS_NPCX_7M6X_JTAG[@]}" "${BOARD}"); then
 	CHIP="npcx_7m6x_jtag"
+elif $(in_array "${BOARDS_NPCX_7M7X_JTAG[@]}" "${BOARD}"); then
+	CHIP="npcx_7m7x_jtag"
 elif $(in_array "${BOARDS_NPCX_SPI[@]}" "${BOARD}"); then
 	CHIP="npcx_spi"
 elif $(in_array "${BOARDS_NPCX_INT_SPI[@]}" "${BOARD}"); then
@@ -298,6 +305,10 @@ servo_sh_hard_reset() {
 	dut_control sh_reset:off
 }
 
+ccd_cr50_ec_hard_reset() {
+	servo_ec_hard_reset
+}
+
 ec_reset() {
 	stype=${SERVO_TYPE}
 	if [[ "${SERVO_TYPE}" =~ "servo" ]] ; then
@@ -353,6 +364,7 @@ on_servov3() {
 error_reported=  # Avoid double printing the error message.
 on_raiden() {
 	if [[ "${SERVO_TYPE}" =~ "servo_v4" ]] || \
+	   [[ "${SERVO_TYPE}" =~ "ccd_cr50" ]] || \
 	   [[ "${SERVO_TYPE}" =~ "servo_micro" ]]; then
 		return 0
 	fi
@@ -384,7 +396,7 @@ cleanup() {
 		kill -CONT ${pid}
 	done
 
-	if ! on_raiden || [[ "${SERVO_TYPE}" =~ "servo_micro" ]] ; then
+	if ! on_raiden || $(servo_has_cold_reset); then
 		ec_reset
 	fi
 }
@@ -442,7 +454,7 @@ function servo_ec_uart() {
 case "${BOARD}" in
 	oak_pd|samus_pd|strago_pd ) MCU="usbpd" ;;
 	chell_pd|glados_pd ) MCU="usbpd" ;;
-	eve_fp|meowth_fp ) MCU="usbpd" ;;
+	meowth_fp ) MCU="usbpd" ;;
 	dingdong|hoho|twinkie ) DUT_CONTROL_CMD="true" ; MCU="ec" ;;
 	*) MCU="ec" ;;
 esac
@@ -588,6 +600,17 @@ function flash_flashrom() {
 		die "no flashrom util found."
 	fi
 
+	# Check whether the SPI flash is internal to the NPCX's EC.
+	#
+	# If the in_array function return non-zero, the script will exit.
+	# Therefore, temporarily ignore errors so we can capture the return
+	# value.
+	set +e
+	local board_is_npcx_internal_spi
+	$(in_array "${BOARDS_NPCX_INT_SPI[@]}" "${BOARD}")
+	board_is_npcx_internal_spi=$?
+	set -e # Okay, don't ignore errors anymore.
+
 	if ! on_servov3; then
 		SERIALNAME=$(get_serial)
 		if [[ "$SERIALNAME" != "" ]] ; then
@@ -605,7 +628,7 @@ function flash_flashrom() {
 		dut_control cold_reset:on
 
 		# If spi flash is in npcx's ec, enable gang programer mode
-		if $(in_array "${BOARDS_NPCX_INT_SPI[@]}" "${BOARD}"); then
+		if [ $board_is_npcx_internal_spi -eq 0 ]; then
 			# Set GP_SEL# as low then start ec
 			dut_control fw_up:on
 			sleep 0.1
@@ -626,6 +649,17 @@ function flash_flashrom() {
 			sleep 1
 		fi
 	else
+		if [ $board_is_npcx_internal_spi -eq 0 ]; then
+			# Set GP_SEL# as low then start ec
+			dut_control cold_reset:on
+			dut_control fw_up:on
+			# sleep 0.1
+			dut_control cold_reset:off
+		else
+			# Assert EC reset.
+			dut_control cold_reset:on
+		fi
+
 		# Temp layout
 		L=/tmp/flash_spi_layout_$$
 
@@ -634,7 +668,6 @@ function flash_flashrom() {
 		FLASHROM_OPTIONS="-i EC_RW -i WP_RO -l "${L}" --ignore-fmap \
 			--fast-verify"
 	fi
-
 
 	# flashrom should report the image size at the end of the output.
 	FLASHROM_CMDLINE="sudo ${FLASHROM} ${FLASHROM_PARAM} --get-size"
@@ -672,7 +705,7 @@ function flash_flashrom() {
 
 	# Generate the correct flashrom command to write the ec.
 	FLASHROM_CMDLINE="${FLASHROM} ${FLASHROM_PARAM}"
-	FLASHROM_CMDLINE+="${FLASHROM_OPTIONS} -w ${T}"
+	FLASHROM_CMDLINE+=" ${FLASHROM_OPTIONS} -w ${T}"
 
 	if [ "${FLAGS_verbose}" = ${FLAGS_TRUE} ]; then
 		echo "Running flashrom:" 1>&2
@@ -683,6 +716,11 @@ function flash_flashrom() {
 
 	rm $T
 
+	# Set GP_SEL# as default to disable GP mode when ec reboots
+	if [ $board_is_npcx_internal_spi -eq 0 ]; then
+		dut_control fw_up:off
+	fi
+
 	if  ! on_raiden || [[ "${SERVO_TYPE}" =~ "servo_micro" ]] ; then
 		# Turn off SPI1 interface on servo
 		dut_control spi1_vref:off spi1_buf_en:off
@@ -690,10 +728,6 @@ function flash_flashrom() {
 			dut_control spi1_buf_on_flex_en:off
 		fi
 
-		# Set GP_SEL# as default to disable GP mode when ec reboots
-		if $(in_array "${BOARDS_NPCX_INT_SPI[@]}" "${BOARD}"); then
-			dut_control fw_up:off
-		fi
 	else
 		rm $L
 	fi
@@ -907,6 +941,10 @@ function flash_npcx_5m6g_jtag() {
 }
 
 function flash_npcx_7m6x_jtag() {
+	flash_npcx_jtag
+}
+
+function flash_npcx_7m7x_jtag() {
 	flash_npcx_jtag
 }
 
