WIP, flash_ec: build bridge to new servod architecture
In the new servod architecture, the main changes affecting flash_ec are
that
(1) there is support for prefix routing to route to the right device
// This requires adding --prefix as a parameter, and some logic to
// ignore it or use it iff the servod is the new architecture and the
// prefix is known

(2) the servo_type does no longer support servo_v4_with_[...] but rather
each device reports their own type.
// This requires adding ccd_cr50 as a standalone device to flash_ec

(3) the serialnames are also no longer required to have special logic,
but rather follow the prefix routing logic i.e. serialname will report
for the device that the control is intended for.
// This needs no adjustment as it works the same as using servo v4,
// servo micro, or ccd by itself now.

BRANCH=None
BUG=chromium:841121
TEST=manual testing

prep:
add echo & exit 0 statements below the new logic

// old servod without prefixes
./flash_ec --prefix lol
WARNING: old servod. no prefix support. prefix 'lol'
dut-control --port=9999

// new servod with an unknown prefix
./flash_ec --prefix lol
ERROR: prefix 'lol' unknown to servod.

// new servod with a known prefix
./flash_ec --prefix support
dut-control --port=9999 --prefix=support

// new servod without a prefix
./flash_ec
dut-control --port=9999

Change-Id: Ib01512a168c205c23507c1a5630677319ae1f6b4
Signed-off-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -154,6 +154,8 @@ DEFINE_string logfile "" \
 	"Stm32 only: pathname of the file to store communications log."
 DEFINE_string offset "0" \
 	"Offset where to program the image from."
+DEFINE_string prefix "" \
+	"Device control prefix for specific servod device (new servod)."
 DEFINE_integer port "${DEFAULT_PORT}" \
 	"Port to communicate to servo on."
 DEFINE_boolean raiden "${FLAGS_FALSE}" \
@@ -183,7 +185,31 @@ MSG_VERIFY_FAIL="Failed to verify EC firmware image."
 
 set -e
 
+
 DUT_CONTROL_CMD=( "dut-control" "--port=${FLAGS_port}" )
+
+
+# This will fail if servod cannot talk on that port but succeed otherwise as
+# it just retrieves a cached value.
+${DUT_CONTROL_CMD[@]} "servod_pid" > /dev/null
+
+
+if [ ! -z  "$FLAGS_prefix" ]; then
+	devs=$(${DUT_CONTROL_CMD[@]} devices 2>&1 | cat)
+	# Test here whether this is the new servod that supports prefixes.
+	if ! [[ $devs =~ "No control named" ]]; then
+		# Test here whether the prefix is known.
+		if [[ $devs =~ "'prefix': '${FLAGS_prefix}'" ]]; then
+			DUT_CONTROL_CMD+=("--prefix=$FLAGS_prefix")
+		else
+			die "prefix '${FLAGS_prefix}' unknown to servod."
+		fi
+	else
+	# Warn the user that prefix was used but it's not supported.
+		warn "old servod. no prefix support. prefix '${FLAGS_prefix}'"
+	fi
+fi
+
 
 function dut_control() {
 	local DUT_CTRL_CML=( "${DUT_CONTROL_CMD[@]}" )
@@ -618,10 +644,11 @@ function servo_ec_uart() {
 # controls are supported by each servo type.
 servo_v2_VARS=( "cold_reset" )
 servo_micro_VARS=( "cold_reset" )
-servo_v4_with_ccd_cr50_VARS=( "cold_reset" )
+ccd_cr50_VARS=( "cold_reset" )
 
 # Some servo boards use the same controls.
 servo_v3_VARS=( "${servo_v2_VARS[@]}" )
+servo_v4_with_ccd_cr50_VARS=( "${ccd_cr50_VARS[@]}" )
 servo_v4_with_servo_micro_VARS=( "${servo_micro_VARS[@]}" )
 toad_VARS=( "boot_mode" )
 
