helipilot: update flash_fp_mcu script with npcx support
BUG=b:293458644
TEST=flash_fp_mcu using Brya + Quincy
TEST=flash_fp_mcu using Brya + Native FPS (bloonchipper)
TEST=flash_fp_mcu using Nipperkin + Quincy
   NOTE: The UART test on Nipperkin + Quincy is failing
     due to a hardware limitation b:293458644 but the
     commands sent via uartupdatetool have been confirmed

Change-Id: I15d9ba2b5439a3ba7ceeb1c7460a77b44fe26338

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -244,6 +244,26 @@ platform_base_name() {
   echo "${base_name//[0-9]/}"
 }
 
+get_chip()
+{
+  local board
+
+  board="$(cros_config /fingerprint board)"
+
+  case "${board}" in
+    bloonchipper|dartmonkey|nocturne_fp|nami_fp)
+      echo "STM32"
+      ;;
+    helipilot)
+      echo "NPCX"
+      ;;
+    *)
+      echo "Error - Unknown board '${board}'." >&2
+      return "${EXIT_CONFIG}"
+      ;;
+  esac
+}
+
 get_default_fw() {
   local board
   board="$(cros_config /fingerprint board)"
@@ -283,53 +303,72 @@ proc_open_file() {
   return "${PIPESTATUS[1]}"
 }
 
-flash_fp_mcu_stm32() {
+flash_fp_mcu_board() {
   local transport="${1}"
   local device="${2}"
   local gpio_nrst="${3}"
   local gpio_boot0="${4}"
   local gpio_pwren="${5}"
   local file="${6}"
-  local deviceid
+  local chip_type="${7}"
 
-  local stm32mon_flags="-p --retries ${STM32MON_CONNECT_RETRIES}"
+  local deviceid=""
+  local cmd_flags=""
 
-  if [[ "${transport}" == "UART" ]]; then
-    stm32mon_flags+=" --baudrate ${FLAGS_baudrate} --device ${device}"
-  else
-    stm32mon_flags+=" -s ${device}"
-  fi
+  echo "# Flashing '${chip_type}' with '${file}' over ${transport}"
 
-  if [[ "${FLAGS_hello}" -eq "${FLAGS_FALSE}" ]]; then
-    if [[ "${FLAGS_remove_flash_write_protect}" -eq "${FLAGS_TRUE}" ]]; then
-      stm32mon_flags+=" -u"
-    fi
+  if [[ "${chip_type}" == "STM32" ]]; then
+    cmd_flags="-p --retries ${STM32MON_CONNECT_RETRIES}"
 
-    if [[ "${FLAGS_remove_flash_read_protect}" -eq "${FLAGS_TRUE}" ]]; then
-      stm32mon_flags+=" -U"
-    fi
-
-    if [[ "${FLAGS_read}" -eq "${FLAGS_TRUE}" ]]; then
-      # Read from FPMCU to file
-      if [[ -e "${file}" ]]; then
-        echo "Output file already exists: ${file}"
-        return "${EXIT_PRECONDITION}"
-      fi
-      echo "# Reading to '${file}' over ${transport}"
-      stm32mon_flags+=" -r ${file}"
+    if [[ "${transport}" == "UART" ]]; then
+      cmd_flags+=" --baudrate ${FLAGS_baudrate} --device ${device}"
     else
-      # Write to FPMCU from file
-      if [[ ! -f "${file}" ]]; then
-        echo "Invalid image file: ${file}"
-        return "${EXIT_PRECONDITION}"
-      fi
-      echo "# Flashing '${file}' over ${transport}"
-      stm32mon_flags+=" -e -w ${file}"
+      cmd_flags+=" -s ${device}"
     fi
-  else
-    echo "# Saying hello over ${transport}"
-  fi
 
+    if [[ "${FLAGS_hello}" -eq "${FLAGS_FALSE}" ]]; then
+      if [[ "${FLAGS_remove_flash_write_protect}" -eq "${FLAGS_TRUE}" ]]; then
+        cmd_flags+=" -u"
+      fi
+
+      if [[ "${FLAGS_remove_flash_read_protect}" -eq "${FLAGS_TRUE}" ]]; then
+        cmd_flags+=" -U"
+      fi
+
+      if [[ "${FLAGS_read}" -eq "${FLAGS_TRUE}" ]]; then
+        # Read from FPMCU to file
+        if [[ -e "${file}" ]]; then
+          echo "Output file already exists: ${file}"
+          return "${EXIT_PRECONDITION}"
+        fi
+        echo "# Reading to '${file}' over ${transport}"
+        cmd_flags+=" -r ${file}"
+      else
+        # Write to FPMCU from file
+        if [[ ! -f "${file}" ]]; then
+          echo "Invalid image file: ${file}"
+          return "${EXIT_PRECONDITION}"
+        fi
+        echo "# Flashing '${file}' over ${transport}"
+        cmd_flags+=" -e -w ${file}"
+      fi
+    else
+      echo "# Saying hello over ${transport}"
+    fi
+  elif [[ "${chip_type}" == "NPCX" ]]; then
+    if [[ "${transport}" == "SPI" ]]; then
+      cmd_flags+=" -p linux_spi:dev=${device},spispeed=250k  -w ${file}"
+    elif [[ "${transport}" == "UART" ]]; then
+      local dev_dir_str="/dev/"
+      local port="${device/"${dev_dir_str}"/""}"
+      cmd_flags+="--port=${port} --baudrate ${FLAGS_baudrate}"
+    fi
+
+    echo "# cmd flags= '${cmd_flags}'"
+  else
+    echo "Unexpected chip_type found: ${chip_type}"
+    return "${EXIT_CONFIG}"
+  fi
 
   check_hardware_write_protect_disabled
 
@@ -403,7 +442,46 @@ flash_fp_mcu_stm32() {
 
   local attempt=0
   local cmd_exit_status=1
-  local cmd="stm32mon ${stm32mon_flags}"
+  local cmd=""
+
+  if [[ "${chip_type}" == "STM32" ]]; then
+    cmd="stm32mon ${cmd_flags}"
+  elif [[ "${chip_type}" == "NPCX" ]]; then
+    if [[ "${transport}" == "SPI" ]]; then
+      cmd="flashrom ${cmd_flags}"
+    elif [[ "${transport}" == "UART" ]]; then
+      # need to flash monitor first before flashing image over UART
+      cmd="uartupdatetool ${cmd_flags}"
+
+      local cmd_flash_monitor=${cmd}
+      cmd_flash_monitor+=" --opr=wr --addr=0x200c3020"
+
+      #TODO(b/294944527): Make sure this file is available in image
+      cmd_flash_monitor+=" --file /opt/google/biod/fw/npcx_monitor.bin"
+
+      # Reset sequence to enter bootloader mode
+      gpio 0 "${gpio_nrst}"
+      sleep 0.01
+
+      # Release reset as the UART bus is now ready
+      gpio 1 "${gpio_nrst}"
+
+      # Print out the actual underlying command we're running and run it
+      echo "# ${cmd_flash_monitor}"
+      ${cmd_flash_monitor}
+      cmd_exit_status=$?
+
+      if [[ "${cmd_exit_status}" -eq 0 ]]; then
+        echo "# NPCX: Flashing monitor PASSED"
+      else
+        # No point to continue if flashing the monitor failed
+        echo "# NPCX: Flashing monitor FAILED!"
+        return "${EXIT_RUNTIME}"
+      fi
+
+      cmd+=" --auto --offset=0 --file ${file}"
+    fi
+  fi
 
   for attempt in $(seq "${FLAGS_retries}"); do
     # Reset sequence to enter bootloader mode
@@ -828,6 +906,7 @@ config_myst() {
 
 main() {
   local filename="$1"
+  local chip_type
 
   # print out canonical path to differentiate between /usr/local/bin and
   # /usr/bin installs
@@ -927,14 +1006,21 @@ main() {
     echo "See b/188985272." >&2
   fi
 
+  if ! chip_type="$(get_chip)"; then
+    echo "Failed to get chip type." >&2
+    exit "${EXIT_CONFIG}"
+  fi
+  echo "Detected chip ${chip_type}."
+
   local ret
-  flash_fp_mcu_stm32 \
+  flash_fp_mcu_board \
     "${TRANSPORT}"   \
     "${DEVICE}"      \
     "${GPIO_NRST}"   \
     "${GPIO_BOOT0}"  \
     "${GPIO_PWREN}"  \
-    "${filename}"
+    "${filename}"    \
+    "${chip_type}"
   ret=$?
 
   if [[ "${FLAGS_services}" -eq "${FLAGS_TRUE}" ]]; then
