flash_ec: npcx: Updating the preserve mechanism
So far we are preserving sections while flashing based on new image,
with this change we will preserve sections based on old image preserve
flags

BUG=b:297804096
TEST=Flashed on Rex, the FMAP partial read approach is not working yet,
there is a bug opened related to that b:299246398

Change-Id: Ib9338a7442717967ac6d366ad7c65cc1d3719e18

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -1595,26 +1595,13 @@ function flash_npcx_uut() {
 		fi
 
 		if [[ "${FLAGS_no_preserve}" == "${FLAGS_FALSE}" ]]; then
-			local CUR_IMG
 			local IMG_CPY
-			local PRESERVE_STATUS
 
-			PRESERVE_STATUS=0
-			is_preservation_needed "${IMG}" "${TEMP_DIR}" || PRESERVE_STATUS=$?
-			if [[ "${PRESERVE_STATUS}" -eq 0 ]]; then
-				info "Reading current EC firmware image."
-				CUR_IMG="${TEMP_DIR}/ec.cur.bin"
-				IMG_CPY="${TEMP_DIR}/ec.new.cpy.bin"
-				cat "${IMG}" > "${IMG_CPY}"
-				IMG="${IMG_CPY}"
-				local UUT_CUR_RD=( "${NPCX_UUT}" "${UUT_ARGS[@]}"   \
-							"--read-flash" "--file=${CUR_IMG}" )
-				echo "${UUT_CUR_RD[*]}"
-				print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
-					"${UUT_CUR_RD[@]}" || die "${MSG_READ_FAIL}"
-
-				preserve_sections "${CUR_IMG}" "${IMG}" "${TEMP_DIR}"
-			fi
+			IMG_CPY="${TEMP_DIR}/ec.new.cpy.bin"
+			cat "${IMG}" > "${IMG_CPY}"
+			IMG="${IMG_CPY}"
+			preserve_sections_npcx "${IMG}" "${TEMP_DIR}"    \
+				"${NPCX_UUT}" "${UUT_ARGS[@]}" || die "${MSG_PROGRAM_FAIL}"
 		fi
 
 		info "Programming EC firmware image."
@@ -1732,17 +1719,76 @@ if [ "${NEED_SERVO}" != "no" ] ; then
 	servo_save
 fi
 
-function is_preservation_needed() {
+function preserve_sections_npcx() {
 	local NEW_IMG
 	local TEMP_DIR
+	local NPCX_UUT
+	local UUT_ARGS
 
-	NEW_IMG=${1:?"missing arg 1: EC image path"}
+	NEW_IMG=${1:?"missing arg 1: New EC image path"}
 	NEW_IMG=$(readlink -f "${NEW_IMG}")
 	TEMP_DIR=${2:?"missing arg 2: Temp directory path"}
-
+	NPCX_UUT=${3:?"missing arg 3: NPCX UUT tool path"}
+	UUT_ARGS=${4:?"missing arg 4: UUT args"}
 	(
 		cd "${TEMP_DIR}"
-		dump_fmap "${NEW_IMG}" -e | grep -q ' preserve'
+		local NEW_FMAP
+		local NEW_FMAP_OFFSET
+		local NEW_FMAP_SIZE
+		local CUR_FMAP_IMG
+		local CUR_IMG
+		local UUT_CUR_FMAP_RD
+
+		NEW_FMAP=$(dump_fmap "${NEW_IMG}" -e FMAP)
+		NEW_FMAP_OFFSET=$(echo "${NEW_FMAP}" | awk '{print $3}')
+		NEW_FMAP_SIZE=$(echo "${NEW_FMAP}" | awk '{print $4}')
+		CUR_FMAP_IMG="${TEMP_DIR}/ec.cur.fmap.bin"
+		CUR_IMG="${TEMP_DIR}/ec.cur.bin"
+		info "Reading FMAP section from EC chip"
+		UUT_CUR_FMAP_RD=( "${NPCX_UUT}" "${UUT_ARGS[@]}"   \
+		  "--opr=rd" "--addr=${NEW_FMAP_OFFSET}"   \
+		  "--size=${NEW_FMAP_SIZE}" "--file=${CUR_FMAP_IMG}")
+		echo "${UUT_CUR_FMAP_RD[*]}"
+		print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+					"${UUT_CUR_FMAP_RD[@]}" || die "${MSG_READ_FAIL}"
+
+		if [[ -z "$(dump_fmap "${CUR_FMAP_IMG}" -e FMAP)" ]]; then
+			local UUT_CUR_RD
+
+			info "FMAP section read failed, reading complete image"
+			UUT_CUR_RD=( "${NPCX_UUT}" "${UUT_ARGS[@]}"   \
+				"--read-flash" "--file=${CUR_IMG}" )
+			echo "${UUT_CUR_RD[*]}"
+			print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+				"${UUT_CUR_RD[@]}" || die "${MSG_READ_FAIL}"
+			preserve_sections "${CUR_IMG}" "${NEW_IMG}" "${TEMP_DIR}"
+		else
+			info "FMAP read is successful from EC flash"
+			dump_fmap "${CUR_FMAP_IMG}" -e | grep ' preserve' | cut \
+				-f1 -d' ' |
+			while read -r line
+			do
+				local SEC_IMG
+				local SEC_FMAP_DUMP
+				local SEC_OFFSET
+				local SEC_SIZE
+				local UUT_NEW_SEC_RD
+
+				SEC_IMG="${TEMP_DIR}/ec.cur.${line}.bin"
+				SEC_FMAP_DUMP=$(dump_fmap "${CUR_FMAP_IMG}" -e "${line}")
+				SEC_OFFSET=$(echo "${SEC_FMAP_DUMP}" | awk '{print $3}')
+				SEC_SIZE=$(echo "${SEC_FMAP_DUMP}" | awk '{print $4}')
+				info "Reading ${line} section from EC chip"
+				UUT_NEW_SEC_RD=( "${NPCX_UUT}" "${UUT_ARGS[@]}"   \
+				"--opr=rd" "--addr=${SEC_OFFSET}"   \
+				"--size=${SEC_SIZE}" "--file=${SEC_IMG}" )
+				echo "${UUT_NEW_SEC_RD[*]}"
+				print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+					"${UUT_NEW_SEC_RD[@]}" || die "${MSG_READ_FAIL}"
+				info "Preserving ${line} section in new image"
+				cbfstool "${NEW_IMG}" write -r "${line}" -f "${SEC_IMG}"
+			done
+		fi
 	)
 }
 
@@ -1757,13 +1803,14 @@ function preserve_sections() {
 	TEMP_DIR=${3:?"missing arg 3: Temp directory path"}
 	(
 		cd "${TEMP_DIR}"
-		dump_fmap "${NEW_IMG}" -e | grep ' preserve' | cut \
+		dump_fmap "${CUR_IMG}" -e | grep ' preserve' | cut \
 			-f1 -d' ' |
 		while read -r line
 		do
-			info "Preserving ${line} section on EC chip"
-			local SEC_IMG="${TEMP_DIR}/ec.cur.${line}.bin"
+			local SEC_IMG
 
+			info "Preserving ${line} section on EC chip"
+			SEC_IMG="${TEMP_DIR}/ec.cur.${line}.bin"
 			cbfstool "${CUR_IMG}" read -r "${line}" -f "${SEC_IMG}"
 			cbfstool "${NEW_IMG}" write -r "${line}" -f "${SEC_IMG}"
 		done
