flash_ec: add "--read" and "--verify" flags for npcx chip.
"--read" takes a following string as a path to store the image file.
If it is specified, flash_ec reads only an EC firmware image and store
it to the given path, but does not program EC firmware.

"--verify" lets flash_ec read EC firmware image after flashing it, and
compare the read image to the source image to check if they match.

CQ-DEPEND=CL:1409497
BUG=b:123044471
BRANCH=none
TEST=manually ran flash_ec on coral.
util/flash_ec --board coral --image ${IMG_PATH} --verify --verbose
util/flash_ec --board coral --read ${TEMP_IMG_PATH} --verbose
util/flash_ec --chip npcx_spi --raiden --image ${IMG_PATH} --verify
util/flash_ec --chip npcx_spi --raiden --read ${TEMP_IMG_PATH}

util/flash_ec --board nocturne --image ${IMG_PATH} --verify --verbose
util/flash_ec --board nocturne --read ${TEMP_IMG_PATH} --verbose

Change-Id: I5461ec7ce0c6d0bdb2eb984d9f7fb73c2f73a420
Signed-off-by: Namyoon Woo <namyoon@chromium.org>

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -229,8 +229,8 @@ DEFINE_integer port "${DEFAULT_PORT}" \
 	"Port to communicate to servo on."
 DEFINE_boolean raiden "${FLAGS_FALSE}" \
 	"Use raiden_debug_spi programmer"
-DEFINE_string read "" \
-	"Stm32 only: pathname of the file to store EC firmware image."
+DEFINE_string read "" "Stm32 and npcx_spi only:"\
+" pathname of the file to store EC firmware image."
 DEFINE_boolean ro "${FLAGS_FALSE}" \
 	"Write only the read-only partition"
 DEFINE_integer timeout 600 \
@@ -238,7 +238,7 @@ DEFINE_integer timeout 600 \
 DEFINE_boolean verbose "${FLAGS_FALSE}" \
 	"Verbose hw control logging"
 DEFINE_boolean verify "${FLAGS_FALSE}" \
-	"Stm32 only: verify EC firmware image after programming."
+	"Stm32 and npcx_spi only: verify EC firmware image after programming."
 
 # Parse command line
 FLAGS_HELP="usage: $0 [flags]"
@@ -386,7 +386,7 @@ if [ "${CHIP}" = "stm32_dfu" -o "${CHIP}" = "it83xx" ]; then
 fi
 
 case "${CHIP}" in
-	"stm32") ;;
+	"stm32"|"npcx_spi") ;;
 	*)
 		if [[ -n "${FLAGS_read}" ]]; then
 			die "The flag is not yet supported on ${CHIP}."
@@ -875,59 +875,83 @@ function flash_flashrom() {
 		# Temp layout
 		L=/tmp/flash_spi_layout_$$
 
-		dump_fmap -F "${IMG}" > "${L}"
+		[[ -z "${FLAGS_read}" ]] && dump_fmap -F "${IMG}" > "${L}"
 
-		FLASHROM_OPTIONS="-i EC_RW -i WP_RO -l "${L}" --ignore-fmap \
-			--fast-verify"
+		FLASHROM_OPTIONS="-i EC_RW -i WP_RO -l "${L}" --ignore-fmap"
+		FLASHROM_OPTIONS+=" --fast-verify"
 	fi
 
-	# flashrom should report the image size at the end of the output.
-	FLASHROM_CMDLINE="sudo ${FLASHROM} ${FLASHROM_PARAM} --get-size"
-	if [ "${FLAGS_verbose}" = ${FLAGS_TRUE} ]; then
-		echo "Running flashrom:" 1>&2
-		echo " ${FLASHROM_CMDLINE}" 1>&2
-	fi
-	SPI_SIZE=$(${FLASHROM_CMDLINE} 2>/dev/null |\
-		       grep -oe '[0-9]\+$') || \
-		die "Failed to determine chip size!"
-	(( SPI_SIZE == 0 )) && die "Chip size is 0!"
-
-	IMG_SIZE=$(stat -c%s "$IMG")
-	PATCH_SIZE=$((${SPI_SIZE} - ${IMG_SIZE}))
-
-	# Temp image
-	T=/tmp/flash_spi_$$
-
-	if [ "${CHIP}" = "npcx_spi" ] ; then
-	{	# Patch temp image up to SPI_SIZE
-		cat $IMG
-		if [[ ${IMG_SIZE} -lt ${SPI_SIZE} ]] ; then
-			dd if=/dev/zero bs=${PATCH_SIZE} count=1 | \
-				tr '\0' '\377'
-		fi
-	} > $T
-	else
-	{	# Patch temp image up to SPI_SIZE
-		if [[ ${IMG_SIZE} -lt ${SPI_SIZE} ]] ; then
-			dd if=/dev/zero bs=${PATCH_SIZE} count=1 | \
-				tr '\0' '\377'
-		fi
-		cat $IMG
-	} > $T
-	fi
-
-	# Generate the correct flashrom command to write the ec.
+	# Generate the correct flashrom command base.
 	FLASHROM_CMDLINE="${FLASHROM} ${FLASHROM_PARAM}"
-	FLASHROM_CMDLINE+=" ${FLASHROM_OPTIONS} -w ${T}"
+	if [[ -z "${FLAGS_read}" ]]; then
+		# Program EC image.
+		# flashrom should report the image size at the end of the output.
+		local FLASHROM_GETSIZE="sudo ${FLASHROM_CMDLINE} --get-size"
+		if [[ "${FLAGS_verbose}" == ${FLAGS_TRUE} ]]; then
+			info "Running flashrom:" 1>&2
+			echo " ${FLASHROM_GETSIZE}" 1>&2
+		fi
+		SPI_SIZE=$(${FLASHROM_GETSIZE} 2>/dev/null |\
+			       grep -oe '[0-9]\+$') || \
+			die "Failed to determine chip size!"
+		(( SPI_SIZE == 0 )) && die "Chip size is 0!"
 
-	if [ "${FLAGS_verbose}" = ${FLAGS_TRUE} ]; then
-		echo "Running flashrom:" 1>&2
-		echo " ${FLASHROM_CMDLINE}" 1>&2
+		IMG_SIZE=$(stat -c%s "${IMG}")
+		PATCH_SIZE=$((${SPI_SIZE} - ${IMG_SIZE}))
+
+		# Temp image
+		T=/tmp/flash_spi_$$
+
+		if [ "${CHIP}" = "npcx_spi" ] ; then
+		{	# Patch temp image up to SPI_SIZE
+			cat $IMG
+			if [[ ${IMG_SIZE} -lt ${SPI_SIZE} ]] ; then
+				dd if=/dev/zero bs=${PATCH_SIZE} count=1 | \
+					tr '\0' '\377'
+			fi
+		} > $T
+		else
+		{	# Patch temp image up to SPI_SIZE
+			if [[ ${IMG_SIZE} -lt ${SPI_SIZE} ]] ; then
+				dd if=/dev/zero bs=${PATCH_SIZE} count=1 | \
+					tr '\0' '\377'
+			fi
+			cat $IMG
+		} > $T
+		fi
+
+		info "Start programming EC firmware image."
+
+		local FLASHROM_WRITE="${FLASHROM_CMDLINE} ${FLASHROM_OPTIONS}"
+		FLASHROM_WRITE+=" -w ${T}"
+		if [[ "${FLAGS_verbose}" == ${FLAGS_TRUE} ]]; then
+			info "Running flashrom:" 1>&2
+			echo " ${FLASHROM_WRITE}" 1>&2
+		fi
+		sudo timeout -k 10 -s 9 "${FLAGS_timeout}" ${FLASHROM_WRITE}
+	else
+		# Read EC image.
+		info "Start reading EC firmware image."
+
+		local FLASHROM_READ="${FLASHROM_CMDLINE} -r ${FLAGS_read}"
+		if [[ "${FLAGS_verbose}" == ${FLAGS_TRUE} ]]; then
+			info "Running flashrom:" 1>&2
+			echo " ${FLASHROM_READ}" 1>&2
+		fi
+		sudo timeout -k 10 -s 9 "${FLAGS_timeout}" ${FLASHROM_READ}
 	fi
-	sudo timeout -k 10 -s 9 "${FLAGS_timeout}" \
-		${FLASHROM_CMDLINE}
+	if [[ -z "${FLAGS_read}" && "${FLAGS_verify}" == ${FLAGS_TRUE} ]]; then
+		# Verify EC image.
+		info "Verify EC firmware image."
 
-	rm $T
+		local FLASHROM_VERIFY="${FLASHROM_CMDLINE} -v ${T}"
+		if [[ "${FLAGS_verbose}" == ${FLAGS_TRUE} ]]; then
+			info "Running flashrom:" 1>&2
+			echo " ${FLASHROM_VERIFY}" 1>&2
+		fi
+		sudo timeout -k 10 -s 9 "${FLAGS_timeout}" ${FLASHROM_VERIFY}
+	fi
+	[[ -f "${T}" ]] && rm "${T}"
 
 	# Set GP_SEL# as default to disable GP mode when ec reboots
 	if [ $board_is_npcx_internal_spi -eq 0 ]; then
@@ -942,7 +966,7 @@ function flash_flashrom() {
 		fi
 
 	else
-		rm $L
+		[[ -f "${L}" ]] && rm "${L}"
 	fi
 
 	# Do not save/restore servo settings
