util/flash_fp_mcu: Replace sysfs with libgpiod
BUG=b:358420799, b:381902143
TEST=none

Cq-Depend: chromium:6713968
Change-Id: Ie8d4e2c011f8fe09c6e555dfaabec34b1917ea1e

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -104,32 +104,26 @@ get_uartid() {
   return 1
 }
 
-# TODO(b/358420799): Replace with libgpiod (gpioget/gpioset).
-# Usage: gpio <unexport|export|in|out|0|1|get> <signal> [signal...]
+# Usage: gpio <0|1|get> <signal> [signal...]
 gpio() {
   local cmd="$1"
   shift
 
+  if [[ -z "${GPIO_CHIP}" ]]; then
+      echo "Error: GPIO_CHIP variable is not set." >&2
+      exit "${EXIT_CONFIG}"
+  fi
+
   for signal in "$@"; do
     case "${cmd}" in
-      unexport|export)
-        klog "Set gpio ${signal} to ${cmd}"
-        echo "${signal}" > "/sys/class/gpio/${cmd}"
-        ;;
-      in|out)
-        local direction="${cmd}"
-        klog "Set gpio ${signal} direction to ${direction}"
-        echo "${direction}" > "/sys/class/gpio/gpio${signal}/direction"
-        ;;
       0|1)
         local value="${cmd}"
-        klog "Set gpio ${signal} to ${value}"
-        echo "${value}" > "/sys/class/gpio/gpio${signal}/value"
+        klog "Set gpio ${GPIO_CHIP}/${signal} to ${value}"
+        gpioset "${GPIO_CHIP}" "${signal}=${value}"
         ;;
       get)
-        local value="${cmd}"
-        klog "Get gpio ${signal}"
-        cat "/sys/class/gpio/gpio${signal}/value"
+        klog "Get gpio ${GPIO_CHIP}/${signal}"
+        gpioget "${GPIO_CHIP}" "${signal}"
         ;;
       *)
         echo "Invalid gpio command: ${cmd}" >&2
@@ -242,14 +236,10 @@ power_cycle_fpmcu() {
 
   if [[ "${gpio_pwren}" -gt 0 ]]; then
     echo "Power cycling the FPMCU."
-    gpio export "${gpio_pwren}"
-    gpio out    "${gpio_pwren}"
     gpio 0      "${gpio_pwren}"
     # Must outlast hardware soft start, which is typically ~3ms.
     sleep 0.5
     gpio 1      "${gpio_pwren}"
-    # Power enable line is externally pulled down, so leave as output-high.
-    gpio unexport "${gpio_pwren}"
   fi
 }
 
@@ -580,10 +570,6 @@ flash_fp_mcu_board() {
     echo "Flashing ${transport} device ID: ${deviceid}"
   fi
 
-  # Configure the MCU Boot0 and NRST GPIOs
-  gpio export "${gpio_boot0}" "${gpio_nrst}"
-  gpio out    "${gpio_boot0}" "${gpio_nrst}"
-
   # Reset sequence to enter bootloader mode
   gpio 1 "${gpio_boot0}"
   gpio 0 "${gpio_nrst}"
@@ -653,26 +639,11 @@ flash_fp_mcu_board() {
     power_cycle_fpmcu "${gpio_pwren}"
   else
     echo "Reset the FPMCU."
-    gpio out	"${gpio_nrst}"
     gpio 0	"${gpio_nrst}"
     # Make sure that we keep nRST line low long enough.
     sleep 0.01
     gpio 1	"${gpio_nrst}"
   fi
-
-  # Give up GPIO control, unless we need to keep these driving as
-  # outputs because they're not open-drain signals.
-  # TODO(b/179839337): Make this the default and properly support
-  # open-drain outputs on other platforms.
-  if [[ "${PLATFORM_BASE_NAME}" != "strongbad" ]] &&
-     [[ "${PLATFORM_BASE_NAME}" != "zork" ]] &&
-     [[ "${PLATFORM_BASE_NAME}" != "myst" ]] &&
-     [[ "${PLATFORM_BASE_NAME}" != "rauru" ]] &&
-     [[ "${PLATFORM_BASE_NAME}" != "skyrim" ]] &&
-     [[ "${PLATFORM_BASE_NAME}" != "skywalker" ]]; then
-    gpio in       "${gpio_boot0}" "${gpio_nrst}"
-  fi
-  gpio unexport "${gpio_boot0}" "${gpio_nrst}"
 
   # Put back cros_fp driver if transport is SPI
   if [[ "${transport}" != "UART" ]]; then
@@ -1317,7 +1288,7 @@ main() {
   fi
 
   # Check that the gpiochip exists
-  if [[ ! -e "/sys/class/gpio/${GPIO_CHIP}" ]]; then
+  if ! gpioinfo "${GPIO_CHIP}" > /dev/null ; then
     echo "Cannot find GPIO chip: ${GPIO_CHIP}"
     exit "${EXIT_CONFIG}"
   fi
