util/flash_fp_mcu: Ensure that spidev kernel module is loaded
BUG=b:381902143
TEST=CQ

Cq-Depend: chromium:6713968
Change-Id: Idf548fa4146feb1854a72380f81bdd557a0f4254

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -72,6 +72,21 @@ os() {
   return 1
 }
 
+check_spidev() {
+  if [[ -d "/sys/module/spidev" ]]; then
+    return 0
+  fi
+
+  if [[ "$(os)" == "android" ]]; then
+    if insmod /vendor/lib/modules/spidev.ko; then
+      return 0
+    fi
+  fi
+
+  echo "Failed to load spidev kernel module" >&2
+  exit "${EXIT_PRECONDITION}"
+}
+
 check_hardware_write_protect_disabled() {
   local hardware_write_protect_state
   if ! hardware_write_protect_state="$(crossystem wpsw_cur)"; then
@@ -1356,6 +1371,9 @@ main() {
     echo "Cannot find GPIO chip: ${GPIO_CHIP}"
     exit "${EXIT_CONFIG}"
   fi
+
+  # Ensure spidev module is loaded.
+  check_spidev
 
   # Ensure hardware write-protect is disabled.
   check_hardware_write_protect_disabled
