dummy commit
Change-Id: I15758a7fcf192d7d61d265b74af608f1cdaf890d

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -1133,6 +1133,28 @@ function flash_flashrom() {
 		} > "${T}"
 		fi
 
+		if [[ "${FLAGS_no_preserve}" == "${FLAGS_FALSE}" ]]; then
+		  local TEMP_DIR
+		  local CUR_IMG
+			local PRESERVE_STATUS
+			TEMP_SUFFIX=".$(basename "${SCRIPT}").${CHIP}.$$"
+			TEMP_DIR="$(mktemp -d --suffix="${TEMP_SUFFIX}")"
+			DELETE_LIST+=("${TEMP_DIR}")
+
+			PRESERVE_STATUS=0
+			is_preservation_needed "${IMG}" "${TEMP_DIR}" || PRESERVE_STATUS=$?
+			if [[ "${PRESERVE_STATUS}" -eq 0 ]]; then
+				info "Reading current EC firmware image."
+				CUR_IMG="${TEMP_DIR}/ec.cur.bin"
+				local FLASH_RD=( "${FLASHROM_CMDLINE[*]} -r ${CUR_IMG}" )
+				echo "${UUT_CUR_RD[*]}"
+				print_or_run timeout -k 10 -s 9 "${FLAGS_timeout}" \
+					"${FLASH_RD[@]}" || die "${MSG_READ_FAIL}"
+
+				preserve_sections "${CUR_IMG}" "${IMG}" "${TEMP_DIR}"
+			fi
+		fi
+
 		info "Programming EC firmware image."
 		local FLASHROM_WRITE=("${FLASHROM_CMDLINE[@]}" "${FLASHROM_OPTIONS[@]}")
 		if [[ "${FLAGS_verbose}" == "${FLAGS_TRUE}" ]]; then
