flash_ec: add "--read" flags for it83xx EC.
"--read" takes a following string as a path to store the image file.
If it is specified, flash_ec reads only an EC firmware image and store
it to the given path.

iteflash verifies the programed EC binary as default, which is
identical to "--verify" design in flash_ec. There is no need to
implement the code handling "--verify" for ITE EC.

CQ-DEPEND=CL:1364327, CL:1481829
BUG=b:123881479
BRANCH=none
TEST=manually ran flash_ec on bip.

[servo_v2 and suzy-Q respectively, on bip]
./util/flash_ec --board bip --read ${IMG_READ}
./util/flash_ec --board bip --image ${IMG} --verify

[servo_v2 and suzy-Q respectively, on dragonegg]
./util/flash_ec --board dragonegg --read ${IMG_READ}
./util/flash_ec --board dragonegg --image ${IMG} --verify

Change-Id: I601c35a6bdab53c97e0742c77550e6bbe220d546
Signed-off-by: Namyoon Woo <namyoon@chromium.org>

diff --git a/util/flash_ec b/util/flash_ec
--- a/util/flash_ec
+++ b/util/flash_ec
@@ -230,7 +230,7 @@ DEFINE_integer port "${DEFAULT_PORT}" \
 	"Port to communicate to servo on."
 DEFINE_boolean raiden "${FLAGS_FALSE}" \
 	"Use raiden_debug_spi programmer"
-DEFINE_string read "" "Stm32 and npcx_(|int_)spi only:"\
+DEFINE_string read "" "Stm32, it83xx and npcx_(|int_)spi only:"\
 " pathname of the file to store EC firmware image."
 DEFINE_boolean ro "${FLAGS_FALSE}" \
 	"Write only the read-only partition"
@@ -238,7 +238,7 @@ DEFINE_integer timeout 600 \
 	"Timeout for flashing the EC, measured in seconds."
 DEFINE_boolean verbose "${FLAGS_FALSE}" \
 	"Verbose hw control logging"
-DEFINE_boolean verify "${FLAGS_FALSE}" "Stm32 and npcx_(int_)spi only:"\
+DEFINE_boolean verify "${FLAGS_FALSE}" "Stm32, it83xx and npcx_(int_)spi only:"\
 " verify EC firmware image after programming."
 
 # Parse command line
@@ -387,7 +387,7 @@ if [ "${CHIP}" = "stm32_dfu" -o "${CHIP}" = "it83xx" ]; then
 fi
 
 case "${CHIP}" in
-	"stm32"|"npcx_spi"|"npcx_int_spi") ;;
+	"stm32"|"npcx_spi"|"npcx_int_spi"|"it83xx") ;;
 	*)
 		if [[ -n "${FLAGS_read}" ]]; then
 			die "The flag is not yet supported on ${CHIP}."
@@ -552,23 +552,30 @@ cleanup() {
 
 	if [ "${CHIP}" == "it83xx" ] ; then
 		info "Reinitialize ftdi_i2c interface"
-		dut_control ftdii2c_cmd:init
-		dut_control ftdii2c_cmd:open
-		dut_control ftdii2c_cmd:setclock
+		if [[ "${SERVO_TYPE}" =~ "ccd_cr50" ]]; then
+			# Reset the dut mux if it exists
+			if $(servo_has_dut_i2c_mux); then
+				# Turn off dut i2c mux
+				dut_control dut_i2c_mux:none
+			fi
+		else
+			dut_control ftdii2c_cmd:init
+			dut_control ftdii2c_cmd:open
+			dut_control ftdii2c_cmd:setclock
 
-		# Reset the dut mux if it exists
-		if $(servo_has_dut_i2c_mux); then
-			# Ensure servo i2c mux is on so we can talk to dut
-			dut_control i2c_mux_en:on
-			dut_control i2c_mux:remote_adc
+			# Reset the dut mux if it exists
+			if $(servo_has_dut_i2c_mux); then
+				# Ensure servo i2c mux is on so we can talk to dut
+				dut_control i2c_mux_en:on
+				dut_control i2c_mux:remote_adc
 
-			# Turn off dut i2c mux
-			dut_control dut_i2c_mux:none
+				# Turn off dut i2c mux
+				dut_control dut_i2c_mux:none
 
-			# Turn off servo i2c mux
-			dut_control i2c_mux_en:off
+				# Turn off servo i2c mux
+				dut_control i2c_mux_en:off
+			fi
 		fi
-
 	fi
 	if [ "${CHIP}" == "stm32" -o "${CHIP}" == "npcx_uut" ] ; then
 		# Reconnect the EC-3PO interpreter to the UART.
@@ -910,7 +917,7 @@ function flash_flashrom() {
 		} > $T
 		fi
 
-		info "Start programming EC firmware image."
+		info "Programming EC firmware image."
 		local FLASHROM_WRITE="${FLASHROM_CMDLINE} ${FLASHROM_OPTIONS}"
 		if [[ "${FLAGS_verbose}" == ${FLAGS_TRUE} ]]; then
 			info "Running flashrom:" 1>&2
@@ -920,7 +927,7 @@ function flash_flashrom() {
 			${FLASHROM_WRITE} -w "${T}"
 	else
 		# Read EC image.
-		info "Start reading EC firmware image."
+		info "Reading EC firmware image."
 		if [[ "${FLAGS_verbose}" == ${FLAGS_TRUE} ]]; then
 			info "Running flashrom:" 1>&2
 			echo " ${FLASHROM_CMDLINE} -r ${FLAGS_read}" 1>&2
@@ -930,7 +937,7 @@ function flash_flashrom() {
 	fi
 	if [[ -z "${FLAGS_read}" && "${FLAGS_verify}" == ${FLAGS_TRUE} ]]; then
 		# Verify EC image.
-		info "Verify EC firmware image."
+		info "Verifying EC firmware image."
 		if [[ "${FLAGS_verbose}" == ${FLAGS_TRUE} ]]; then
 			info "Running flashrom:" 1>&2
 			echo " ${FLASHROM_CMDLINE} -v ${T}" 1>&2
@@ -1018,10 +1025,10 @@ function flash_stm32() {
 		STM32MON_OPT+=" -L ${FLAGS_logfile}"
 	fi
 
-	local IMG_READ=""
+	local IMG_READ="${FLAGS_read}"
 	# Program EC image.
-	if [[ -z "${FLAGS_read}" ]]; then
-		info "Start programming EC firmware image."
+	if [[ -z "${IMG_READ}" ]]; then
+		info "Programming EC firmware image."
 		# Unprotect flash, erase, and write
 		local STM32MON_COMMAND="${STM32MON} ${STM32MON_OPT} -u -e -w"
 		if [[ "${FLAGS_verbose}" == ${FLAGS_TRUE} ]]; then
@@ -1033,17 +1040,15 @@ function flash_stm32() {
 		# If it is a program-verify request, then make a temporary
 		# directory to store the image
 		if [[ "${FLAGS_verify}" == ${FLAGS_TRUE} ]]; then
-			local TEMP_SUFFIX=".$(basename ${SCRIPT}).${BOARD}"
+			local TEMP_SUFFIX=".$(basename ${SCRIPT}).${CHIP}"
 			TEMP_DIR="$(mktemp -d --suffix="${TEMP_SUFFIX}")"
 			IMG_READ="${TEMP_DIR}/ec.read.bin"
 		fi
-	else
-		IMG_READ="${FLAGS_read}"
 	fi
 
 	# Read EC image.
 	if [[ -n "${IMG_READ}" ]]; then
-		info "Start reading EC firmware image."
+		info "Reading EC firmware image."
 		local STM32MON_READ_CMD="${STM32MON} ${STM32MON_OPT} -U -r"
 		if [[ "${FLAGS_verbose}" == ${FLAGS_TRUE} ]]; then
 			echo "${STM32MON_READ_CMD} ${IMG_READ}"
@@ -1054,9 +1059,8 @@ function flash_stm32() {
 
 	# Verify the flash by comparing the source image to the read image,
 	# only if it was a flash write request.
-	if [[ -z "${FLAGS_read}" && \
-		"${FLAGS_verify}" == ${FLAGS_TRUE} ]]; then
-		info "Verify EC firmware image."
+	if [[ -z "${FLAGS_read}" && "${FLAGS_verify}" == ${FLAGS_TRUE} ]]; then
+		info "Verifying EC firmware image."
 		if [[ "${FLAGS_verbose}" == ${FLAGS_TRUE} ]]; then
 			echo "diff ${IMG} ${IMG_READ}"
 		fi
@@ -1099,32 +1103,83 @@ function flash_stm32_dfu() {
 }
 
 function flash_it83xx() {
-
 	TOOL_PATH="${EC_DIR}/build/${BOARD}/util:$PATH"
 	ITEFLASH=$(PATH="${TOOL_PATH}" which iteflash)
 	if [ ! -x "$ITEFLASH" ]; then
 		die "no iteflash util found."
 	fi
 
-	dut_control i2c_mux_en:on
-	dut_control i2c_mux:remote_adc
-
-	# Now the we have enabled the I2C mux on the servo to talk to the dut,
-	# we need to switch the I2C mux on the dut to allow ec programing (if
-	# there is a mux on the dut)
-	if $(servo_has_dut_i2c_mux); then
-		dut_control dut_i2c_mux:ec_prog
+	if [[ ${SERVO_TYPE} =~ "servo_v2" ]]; then
+		dut_control i2c_mux_en:on
+		dut_control i2c_mux:remote_adc
 	fi
 
-	# Ensure that the AP is off while we are flashing the EC
-	servo_ec_hard_reset
+	# Now the we have enabled the I2C mux on the servo to talk to
+	# the dut, we need to switch the I2C mux on the dut to allow ec
+	# programing (if there is a mux on the dut)
+	if $(servo_has_dut_i2c_mux); then
+		set +e
+		local retry_count=3
+		while :; do
+			dut_control dut_i2c_mux:ec_prog
+			[[ $? -eq 0 ]] && break
+			sleep 5
+			let retry_count-=1
+			[[ ${retry_count} -eq 0 ]] && die "dut_i2c_mux failed."
+		done
+		set -e
+	fi
 
-	info "Close connection to ftdi_i2c interface"
-	dut_control ftdii2c_cmd:close
+ 	if [[ "${SERVO_TYPE}" =~ "servo_v2" ]]; then
+		# Ensure that the AP is off while we are flashing the EC
+		servo_ec_hard_reset
 
-	info "Run iteflash..."
-	sudo "${ITEFLASH}" --i2c-interface=ftdi --send-waveform=1 --erase \
-		--write="${IMG}"
+		info "Close connection to ftdi_i2c interface"
+		dut_control ftdii2c_cmd:close
+	elif [[ "${SERVO_TYPE}" =~ "ccd_cr50" ]]; then
+		info "Triggering to send the dbgr special waveform to EC..."
+		dut_control cr50_i2c_ctrl:ite_sync
+
+		sleep 3
+	fi
+
+	declare -a ITEFLASH_PARAM
+	if [[ "${SERVO_TYPE}" =~ "ccd_cr50" ]]; then
+		ITEFLASH_PARAM+=("--send-waveform=0")
+		ITEFLASH_PARAM+=("--i2c-interface=ccd")
+	else
+		ITEFLASH_PARAM+=("--send-waveform=1")
+		ITEFLASH_PARAM+=("--i2c-interface=ftdi")
+	fi
+
+	if [[ "${FLAGS_verbose}" == ${FLAGS_TRUE} ]]; then
+		ITEFLASH_PARAM+=("--debug")
+	fi
+
+	local IMG_READ="${FLAGS_read}"
+	# Program EC Image
+	if [[ -z "${IMG_READ}" ]]; then
+		info "Programming EC firmware image"
+		if [[ "${FLAGS_verbose}" == ${FLAGS_TRUE} ]]; then
+			echo "${ITEFLASH}" "${ITEFLASH_PARAM[@]}" --erase \
+				--write="${IMG}"
+		fi
+		sudo "${ITEFLASH}" "${ITEFLASH_PARAM[@]}" --erase \
+			--write="${IMG}"
+
+		# iteflash verifies the programmed EC binary by reading it
+		# back as default. No need to verify here.
+	fi
+
+	# Read EC Image
+	if [[ -n "${IMG_READ}" ]]; then
+		info "Reading EC firmware image"
+		if [[ "${FLAGS_verbose}" == ${FLAGS_TRUE} ]]; then
+			echo "${ITEFLASH}" "${ITEFLASH_PARAM[@]}" \
+			--read="${IMG_READ}"
+		fi
+		sudo "${ITEFLASH}" "${ITEFLASH_PARAM[@]}" --read "${IMG_READ}"
+	fi
 }
 
 function flash_lm4() {
