flash_fp_mcu: add a config for the screebo fingerprint MCU
Screebo is a rex family, on Screebo, only NRST/BOOT0/PWREN has
changed, add a config for Screebo to enable update the fingerprint
MCU firmware features.

BUG=b:278156430
TEST=flash_fp_mcu /opt/google/bios/fw/xxx.bin

Change-Id: Iae897a38f55dbab81822fecc684ecbb5fa2a7919
Signed-off-by: Simon Zhou <zhouguohui@huaqin.corp-partner.google.com>

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -700,24 +700,72 @@ config_ghost() {
   config_brya
 }
 
-config_rex() {
-  readonly TRANSPORT="SPI"
-  readonly DEVICE="/dev/spidev0.0"
-
+config_rex0() {
   # See kernel/v5.15/drivers/pinctrl/intel/pinctrl-meteorlake.c
   # for pin name and pin number.
   # Examine `cat /sys/kernel/debug/pinctrl/INTC1083:00/gpio-ranges` on a
   # rex device to determine gpio number from pin number.
   # For example: GPP_B11, the pin number is 215 from the pinctrl-meteorlake.c.
-  # From the gpio-ranges, the gpio value is 925 + (215-204) = 936
+  # From the gpio-ranges, the gpio value is 925 + (215-204) - 573 = 363
 
-  readonly GPIO_CHIP="gpiochip573"
-  # FPMCU RST_ODL is on GPP_C23 = 637 + (52 - 29) = 660
-  readonly GPIO_NRST=660
-  # FPMCU BOOT0 is on GPP_C22 = 637 + (51 - 29) = 659
-  readonly GPIO_BOOT0=659
-  # FP_PWR_EN is on GPP_B11 = 925 + (215-204) = 936
-  readonly GPIO_PWREN=936
+  local gpiobase="$1"
+  # FPMCU RST_ODL is on GPP_C23 = 637 + (52 - 29) - 573 = 87
+  local gpionrst=87
+  readonly GPIO_NRST=$(( gpionrst + gpiobase ))
+  # FPMCU BOOT0 is on GPP_C22 = 637 + (51 - 29) - 573 = 86
+  local gpioboot=86
+  readonly GPIO_BOOT0=$(( gpioboot + gpiobase ))
+  # FP_PWR_EN is on GPP_B11 = 925 + (215-204) - 573 = 363
+  local gpiopwren=363
+  readonly GPIO_PWREN=$(( gpiopwren + gpiobase ))
+}
+
+config_screebo() {
+  # screebo is a rex family.
+  # See kernel/v5.15/drivers/pinctrl/intel/pinctrl-meteorlake.c
+  # for pin name and pin number.
+  # Examine `cat /sys/kernel/debug/pinctrl/INTC1083:00/gpio-ranges` on a
+  # rex device to determine gpio number from pin number.
+  # For example: GPP_B11, the pin number is 215 from the pinctrl-meteorlake.c.
+  # From the gpio-ranges, the gpio value is 925 + (215-204) - 573 = 363
+
+  local gpiobase="$1"
+  # FPMCU RST_ODL is on GPP_C21 = 637 + (50 - 29) - 573 = 85
+  local gpionrst=85
+  readonly GPIO_NRST=$(( gpionrst + gpiobase ))
+  # FPMCU BOOT0 is on GPP_C20 = 637 + (49 - 29) - 573 = 84
+  local gpioboot=84
+  readonly GPIO_BOOT0=$(( gpioboot + gpiobase ))
+  # FP_PWR_EN is on GPP_B08 = 925 + (212-204) - 573 = 360
+  local gpiopwren=360
+  readonly GPIO_PWREN=$(( gpiopwren + gpiobase ))
+}
+
+config_rex() {
+  readonly TRANSPORT="SPI"
+  readonly DEVICE="/dev/spidev0.0"
+
+  local gpiochip_dev_path="*/pci0000:00/INTC1083\:00/gpio/*"
+  local gpiobase
+  if ! gpiobase=$(get_sysfs_gpiochip_base "${gpiochip_dev_path}"); then
+    echo "Unable to find gpio chip base"
+    return "${EXIT_PRECONDITION}"
+  fi
+
+  readonly GPIO_CHIP="gpiochip${gpiobase}"
+
+  local model=$(cros_config / name)
+  # Check that the config function exists
+  if [[ "$(type -t "config_${model}")" == "function" ]]; then
+    echo "Config for model: ${model}." >&2
+    if ! "config_${model} ${gpiobase}"; then
+      echo "Configuration failed for model ${model}." >&2
+      exit "${EXIT_CONFIG}"
+    fi
+  else
+    echo "No config for model ${model}." >&2
+    exit "${EXIT_CONFIG}"
+  fi
 }
 
 config_zork() {
